// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using production_supply_system.EntityFramework.DAL.Models.CustomsSchema;
using production_supply_system.EntityFramework.DAL.Models.dboSchema;
using production_supply_system.EntityFramework.DAL.Models.DocmapperSchema;
using production_supply_system.EntityFramework.DAL.Models.InboundSchema;
using production_supply_system.EntityFramework.DAL.Models.MasterSchema;
using production_supply_system.EntityFramework.DAL.Models.PartscontrolSchema;
using production_supply_system.EntityFramework.DAL.Models.PlanningSchema;
using production_supply_system.EntityFramework.DAL.Models.UsersSchema;


namespace production_supply_system.EntityFramework.DAL.Models.DocmapperSchema;

[Table("tbd_Docmapper_Columns", Schema = "Docmapper")]
public partial class DocmapperColumn
{
    [Key]
    [Column("Docmapper_Column_Id")]
    public int DocmapperColumnId { get; set; }

    [Column("Element_Name")]
    [StringLength(50)]
    public string ElementName { get; set; } = null!;

    [Column("System_Column_Name")]
    [StringLength(50)]
    public string SystemColumnName { get; set; } = null!;

    [InverseProperty("DocmapperColumn")]
    public virtual ICollection<DocmapperContent> DocmapperContents { get; set; } = new List<DocmapperContent>();
}