// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using production_supply_system.EntityFramework.DAL.Models.CustomsSchema;
using production_supply_system.EntityFramework.DAL.Models.dboSchema;
using production_supply_system.EntityFramework.DAL.Models.DocmapperSchema;
using production_supply_system.EntityFramework.DAL.Models.InboundSchema;
using production_supply_system.EntityFramework.DAL.Models.MasterSchema;
using production_supply_system.EntityFramework.DAL.Models.PartscontrolSchema;
using production_supply_system.EntityFramework.DAL.Models.PlanningSchema;
using production_supply_system.EntityFramework.DAL.Models.UsersSchema;


namespace production_supply_system.EntityFramework.DAL.Models.DocmapperSchema;

[Table("tbd_Docmapper_Content", Schema = "Docmapper")]
public partial class DocmapperContent
{
    [Key]
    [Column("Docmapper_Content_Id")]
    public int DocmapperContentId { get; set; }

    [Column("Docmapper_Id")]
    public int DocmapperId { get; set; }

    [Column("Docmapper_Column_Id")]
    public int DocmapperColumnId { get; set; }

    [Column("Row_Nr")]
    public int? RowNr { get; set; }

    [Column("Column_Nr")]
    public int ColumnNr { get; set; }

    [ForeignKey("DocmapperId")]
    [InverseProperty("DocmapperContents")]
    public virtual Docmapper Docmapper { get; set; } = null!;

    [ForeignKey("DocmapperColumnId")]
    [InverseProperty("DocmapperContents")]
    public virtual DocmapperColumn DocmapperColumn { get; set; } = null!;
}