// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using production_supply_system.EntityFramework.DAL.Models.CustomsSchema;
using production_supply_system.EntityFramework.DAL.Models.dboSchema;
using production_supply_system.EntityFramework.DAL.Models.DocmapperSchema;
using production_supply_system.EntityFramework.DAL.Models.InboundSchema;
using production_supply_system.EntityFramework.DAL.Models.MasterSchema;
using production_supply_system.EntityFramework.DAL.Models.PartscontrolSchema;
using production_supply_system.EntityFramework.DAL.Models.PlanningSchema;
using production_supply_system.EntityFramework.DAL.Models.UsersSchema;


namespace production_supply_system.EntityFramework.DAL.Models.UsersSchema;

[Table("tbd_Users", Schema = "Users")]
[Index("Account", Name = "UQ_tbd_Users_Account", IsUnique = true)]
public partial class User
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [StringLength(10)]
    public string Account { get; set; } = null!;

    [StringLength(30)]
    public string Name { get; set; } = null!;

    [StringLength(30)]
    public string Surname { get; set; } = null!;

    [StringLength(30)]
    public string Patronymic { get; set; } = null!;

    [Column("Section_Id")]
    public int SectionId { get; set; }

    [ForeignKey("SectionId")]
    [InverseProperty("Users")]
    public virtual Section Section { get; set; } = null!;
}