// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using production_supply_system.EntityFramework.DAL.Models.CustomsSchema;
using production_supply_system.EntityFramework.DAL.Models.dboSchema;
using production_supply_system.EntityFramework.DAL.Models.DocmapperSchema;
using production_supply_system.EntityFramework.DAL.Models.InboundSchema;
using production_supply_system.EntityFramework.DAL.Models.MasterSchema;
using production_supply_system.EntityFramework.DAL.Models.PartscontrolSchema;
using production_supply_system.EntityFramework.DAL.Models.PlanningSchema;
using production_supply_system.EntityFramework.DAL.Models.UsersSchema;


namespace production_supply_system.EntityFramework.DAL.Models.InboundSchema;

[Table("tbd_Containers_In_Lot", Schema = "Inbound")]
public partial class ContainersInLot
{
    [Key]
    [Column("Container_In_Lot_Id")]
    public int ContainerInLotId { get; set; }

    [Column("Lot_Id")]
    public int LotId { get; set; }

    [Column("Container_Number")]
    [StringLength(11)]
    public string ContainerNumber { get; set; } = null!;

    [Column("Seal_Number")]
    [StringLength(20)]
    public string? SealNumber { get; set; }

    [Column("Container_Type_Id")]
    public int ContainerTypeId { get; set; }

    [Column("IMO_Cargo")]
    public bool? ImoCargo { get; set; }

    [Column("Storage_Last_Free_Day")]
    public DateOnly? StorageLastFreeDay { get; set; }

    [Column("Detention_Last_Free_Day")]
    public DateOnly? DetentionLastFreeDay { get; set; }

    [Column("Container_Comment")]
    [StringLength(250)]
    public string? ContainerComment { get; set; }

    [Column("Last_Tracing_Update")]
    public DateOnly? LastTracingUpdate { get; set; }

    [Column("CI_OnTheWay")]
    public bool CiOnTheWay { get; set; }

    [ForeignKey("ContainerTypeId")]
    [InverseProperty("ContainersInLots")]
    public virtual TypesOfContainer ContainerType { get; set; } = null!;

    [ForeignKey("LotId")]
    [InverseProperty("ContainersInLots")]
    public virtual Lot Lot { get; set; } = null!;

    [InverseProperty("ContainerInLot")]
    public virtual ICollection<CustomsClearance> CustomsClearances { get; set; } = new List<CustomsClearance>();

    [InverseProperty("ContainerInLot")]
    public virtual ICollection<PartsInContainer> PartsInContainers { get; set; } = new List<PartsInContainer>();

    [InverseProperty("ContainerInLot")]
    public virtual ICollection<Tracing> Tracings { get; set; } = new List<Tracing>();

    [InverseProperty("ContainerInLot")]
    public virtual ICollection<VinsInContainer> VinsInContainers { get; set; } = new List<VinsInContainer>();
}