// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using production_supply_system.EntityFramework.DAL.Models.CustomsSchema;
using production_supply_system.EntityFramework.DAL.Models.dboSchema;
using production_supply_system.EntityFramework.DAL.Models.DocmapperSchema;
using production_supply_system.EntityFramework.DAL.Models.InboundSchema;
using production_supply_system.EntityFramework.DAL.Models.MasterSchema;
using production_supply_system.EntityFramework.DAL.Models.PartscontrolSchema;
using production_supply_system.EntityFramework.DAL.Models.PlanningSchema;
using production_supply_system.EntityFramework.DAL.Models.UsersSchema;


namespace production_supply_system.EntityFramework.DAL.Models.InboundSchema;

[Table("tbd_Carriers", Schema = "Inbound")]
public partial class Carrier
{
    [Key]
    [Column("Carrier_Id")]
    public int CarrierId { get; set; }

    [Column("Carrier_Name")]
    [StringLength(50)]
    public string CarrierName { get; set; } = null!;

    [InverseProperty("Carrier")]
    public virtual ICollection<Lot> Lots { get; set; } = new List<Lot>();

    [InverseProperty("Carrier")]
    public virtual ICollection<TermsOfContainerUse> TermsOfContainerUses { get; set; } = new List<TermsOfContainerUse>();

    [InverseProperty("Carrier")]
    public virtual ICollection<Tracing> Tracings { get; set; } = new List<Tracing>();
}