// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using production_supply_system.EntityFramework.DAL.Models.CustomsSchema;
using production_supply_system.EntityFramework.DAL.Models.dboSchema;
using production_supply_system.EntityFramework.DAL.Models.DocmapperSchema;
using production_supply_system.EntityFramework.DAL.Models.InboundSchema;
using production_supply_system.EntityFramework.DAL.Models.MasterSchema;
using production_supply_system.EntityFramework.DAL.Models.PartscontrolSchema;
using production_supply_system.EntityFramework.DAL.Models.PlanningSchema;
using production_supply_system.EntityFramework.DAL.Models.UsersSchema;


namespace production_supply_system.EntityFramework.DAL.Models.InboundSchema;

[Table("tbd_Invoices", Schema = "Inbound")]
[Index("InvoiceNumber", Name = "IX_tbd_Invoices", IsUnique = true)]
public partial class Invoice
{
    [Key]
    [Column("Invoice_Id")]
    public int InvoiceId { get; set; }

    [Column("Invoice_Number")]
    [StringLength(20)]
    public string InvoiceNumber { get; set; } = null!;

    [Column("Invoice_Date")]
    public DateOnly InvoiceDate { get; set; }

    [Column("Shipper_Id")]
    public int ShipperId { get; set; }

    [Column("Purchase_Order_Id")]
    public int? PurchaseOrderId { get; set; }

    [ForeignKey("PurchaseOrderId")]
    [InverseProperty("Invoices")]
    public virtual PurchaseOrder? PurchaseOrder { get; set; }

    [InverseProperty("LotInvoice")]
    public virtual ICollection<Lot> Lots { get; set; } = new List<Lot>();

    [InverseProperty("PartInvoice")]
    public virtual ICollection<PartsInContainer> PartsInContainers { get; set; } = new List<PartsInContainer>();

    [InverseProperty("Invoice")]
    public virtual ICollection<PartsInInvoice> PartsInInvoices { get; set; } = new List<PartsInInvoice>();
}