// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using production_supply_system.EntityFramework.DAL.Models.CustomsSchema;
using production_supply_system.EntityFramework.DAL.Models.dboSchema;
using production_supply_system.EntityFramework.DAL.Models.DocmapperSchema;
using production_supply_system.EntityFramework.DAL.Models.InboundSchema;
using production_supply_system.EntityFramework.DAL.Models.MasterSchema;
using production_supply_system.EntityFramework.DAL.Models.PartscontrolSchema;
using production_supply_system.EntityFramework.DAL.Models.PlanningSchema;
using production_supply_system.EntityFramework.DAL.Models.UsersSchema;


namespace production_supply_system.EntityFramework.DAL.Models.InboundSchema;

[Table("tbd_Locations", Schema = "Inbound")]
public partial class Location
{
    [Key]
    [Column("Location_Id")]
    public int LocationId { get; set; }

    [Column("Location_Type_Id")]
    public int LocationTypeId { get; set; }

    [Column("Location_Name")]
    [StringLength(50)]
    public string LocationName { get; set; } = null!;

    [StringLength(50)]
    public string? City { get; set; }

    [ForeignKey("LocationTypeId")]
    [InverseProperty("Locations")]
    public virtual TypesOfLocation LocationType { get; set; } = null!;

    [InverseProperty("LotArrivalLocation")]
    public virtual ICollection<Lot> LotLotArrivalLocations { get; set; } = new List<Lot>();

    [InverseProperty("LotCustomsLocation")]
    public virtual ICollection<Lot> LotLotCustomsLocations { get; set; } = new List<Lot>();

    [InverseProperty("LotDepartureLocation")]
    public virtual ICollection<Lot> LotLotDepartureLocations { get; set; } = new List<Lot>();

    [InverseProperty("ShipperDefaultDeliveryLocation")]
    public virtual ICollection<Shipper> Shippers { get; set; } = new List<Shipper>();

    [InverseProperty("TraceLocation")]
    public virtual ICollection<Tracing> Tracings { get; set; } = new List<Tracing>();
}