// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using production_supply_system.EntityFramework.DAL.Models.CustomsSchema;
using production_supply_system.EntityFramework.DAL.Models.dboSchema;
using production_supply_system.EntityFramework.DAL.Models.DocmapperSchema;
using production_supply_system.EntityFramework.DAL.Models.InboundSchema;
using production_supply_system.EntityFramework.DAL.Models.MasterSchema;
using production_supply_system.EntityFramework.DAL.Models.PartscontrolSchema;
using production_supply_system.EntityFramework.DAL.Models.PlanningSchema;
using production_supply_system.EntityFramework.DAL.Models.UsersSchema;


namespace production_supply_system.EntityFramework.DAL.Models.InboundSchema;

[Table("tbd_Parts_In_Invoice", Schema = "Inbound")]
public partial class PartsInInvoice
{
    [Key]
    [Column("Part_In_Invoice_Id")]
    public int PartInInvoiceId { get; set; }

    [Column("Invoice_Id")]
    public int InvoiceId { get; set; }

    [Column("Part_Number_Id")]
    public int PartNumberId { get; set; }

    [Column(TypeName = "decimal(8, 3)")]
    public decimal Quantity { get; set; }

    [Column(TypeName = "decimal(10, 4)")]
    public decimal Price { get; set; }

    [ForeignKey("InvoiceId")]
    [InverseProperty("PartsInInvoices")]
    public virtual Invoice Invoice { get; set; } = null!;

    [ForeignKey("PartNumberId")]
    [InverseProperty("PartsInInvoices")]
    public virtual CustomsPart PartNumber { get; set; } = null!;
}