// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using production_supply_system.EntityFramework.DAL.Models.CustomsSchema;
using production_supply_system.EntityFramework.DAL.Models.dboSchema;
using production_supply_system.EntityFramework.DAL.Models.DocmapperSchema;
using production_supply_system.EntityFramework.DAL.Models.InboundSchema;
using production_supply_system.EntityFramework.DAL.Models.MasterSchema;
using production_supply_system.EntityFramework.DAL.Models.PartscontrolSchema;
using production_supply_system.EntityFramework.DAL.Models.PlanningSchema;
using production_supply_system.EntityFramework.DAL.Models.UsersSchema;


namespace production_supply_system.EntityFramework.DAL.Models.InboundSchema;

[Table("tbd_Shippers", Schema = "Inbound")]
public partial class Shipper
{
    [Key]
    [Column("Shipper_Id")]
    public int ShipperId { get; set; }

    [Column("Shipper_Name")]
    [StringLength(20)]
    public string ShipperName { get; set; } = null!;

    [Column("Shipper_Full_Name")]
    [StringLength(100)]
    public string? ShipperFullName { get; set; }

    [Column("Shipper_Default_Delivery_Location_Id")]
    public int? ShipperDefaultDeliveryLocationId { get; set; }

    [ForeignKey("ShipperDefaultDeliveryLocationId")]
    [InverseProperty("Shippers")]
    public virtual Location? ShipperDefaultDeliveryLocation { get; set; }

    [InverseProperty("Shipper")]
    public virtual ICollection<Lot> Lots { get; set; } = new List<Lot>();

    [InverseProperty("Shipper")]
    public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; } = new List<PurchaseOrder>();
}