// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using production_supply_system.EntityFramework.DAL.Models.CustomsSchema;
using production_supply_system.EntityFramework.DAL.Models.dboSchema;
using production_supply_system.EntityFramework.DAL.Models.DocmapperSchema;
using production_supply_system.EntityFramework.DAL.Models.InboundSchema;
using production_supply_system.EntityFramework.DAL.Models.MasterSchema;
using production_supply_system.EntityFramework.DAL.Models.PartscontrolSchema;
using production_supply_system.EntityFramework.DAL.Models.PlanningSchema;
using production_supply_system.EntityFramework.DAL.Models.UsersSchema;


namespace production_supply_system.EntityFramework.DAL.Models.InboundSchema;

[Table("tbd_Types_Of_Packing", Schema = "Inbound")]
public partial class TypesOfPacking
{
    [Key]
    [Column("Packing_Type_Id")]
    public int PackingTypeId { get; set; }

    [Column("Supplier_Packing_Type")]
    [StringLength(150)]
    public string SupplierPackingType { get; set; } = null!;

    [Column("Packing_Type")]
    [StringLength(150)]
    public string PackingType { get; set; } = null!;

    [InverseProperty("PackingType")]
    public virtual ICollection<Case> Cases { get; set; } = new List<Case>();
}