// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using production_supply_system.EntityFramework.DAL.Models.CustomsSchema;
using production_supply_system.EntityFramework.DAL.Models.dboSchema;
using production_supply_system.EntityFramework.DAL.Models.DocmapperSchema;
using production_supply_system.EntityFramework.DAL.Models.InboundSchema;
using production_supply_system.EntityFramework.DAL.Models.MasterSchema;
using production_supply_system.EntityFramework.DAL.Models.PartscontrolSchema;
using production_supply_system.EntityFramework.DAL.Models.PlanningSchema;
using production_supply_system.EntityFramework.DAL.Models.UsersSchema;


namespace production_supply_system.EntityFramework.DAL.Models.InboundSchema;

[Table("tbd_Transports", Schema = "Inbound")]
[Index("TransportName", Name = "IX_tbd_Transports", IsUnique = true)]
public partial class Transport
{
    [Key]
    [Column("Transport_Id")]
    public int TransportId { get; set; }

    [Column("Transport_Name")]
    [StringLength(50)]
    public string TransportName { get; set; } = null!;

    [InverseProperty("LotTransport")]
    public virtual ICollection<Lot> Lots { get; set; } = new List<Lot>();

    [InverseProperty("TraceTransport")]
    public virtual ICollection<Tracing> Tracings { get; set; } = new List<Tracing>();
}