// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using production_supply_system.EntityFramework.DAL.Models.CustomsSchema;
using production_supply_system.EntityFramework.DAL.Models.dboSchema;
using production_supply_system.EntityFramework.DAL.Models.DocmapperSchema;
using production_supply_system.EntityFramework.DAL.Models.InboundSchema;
using production_supply_system.EntityFramework.DAL.Models.MasterSchema;
using production_supply_system.EntityFramework.DAL.Models.PartscontrolSchema;
using production_supply_system.EntityFramework.DAL.Models.PlanningSchema;
using production_supply_system.EntityFramework.DAL.Models.UsersSchema;


namespace production_supply_system.EntityFramework.DAL.Models.InboundSchema;

[Table("tbd_Types_Of_Container", Schema = "Inbound")]
public partial class TypesOfContainer
{
    [Key]
    [Column("Container_Type_Id")]
    public int ContainerTypeId { get; set; }

    [Column("Container_Type")]
    [StringLength(10)]
    public string ContainerType { get; set; } = null!;

    [InverseProperty("ContainerType")]
    public virtual ICollection<ContainersInLot> ContainersInLots { get; set; } = new List<ContainersInLot>();
}