// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using production_supply_system.EntityFramework.DAL.Models.CustomsSchema;
using production_supply_system.EntityFramework.DAL.Models.dboSchema;
using production_supply_system.EntityFramework.DAL.Models.DocmapperSchema;
using production_supply_system.EntityFramework.DAL.Models.InboundSchema;
using production_supply_system.EntityFramework.DAL.Models.MasterSchema;
using production_supply_system.EntityFramework.DAL.Models.PartscontrolSchema;
using production_supply_system.EntityFramework.DAL.Models.PlanningSchema;
using production_supply_system.EntityFramework.DAL.Models.UsersSchema;


namespace production_supply_system.EntityFramework.DAL.Models.InboundSchema;

[Table("tbd_Types_Of_Transport", Schema = "Inbound")]
public partial class TypesOfTransport
{
    [Key]
    [Column("Transport_Type_Id")]
    public int TransportTypeId { get; set; }

    [Column("Transport_Type")]
    [StringLength(10)]
    public string TransportType { get; set; } = null!;

    [Column("Transport_Document_Name")]
    [StringLength(10)]
    public string TransportDocumentName { get; set; } = null!;

    [InverseProperty("LotTransportType")]
    public virtual ICollection<Lot> Lots { get; set; } = new List<Lot>();

    [InverseProperty("TransportationType")]
    public virtual ICollection<Tracing> Tracings { get; set; } = new List<Tracing>();
}