//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI_Interface.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UI_Interface.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Production Supply System.
        /// </summary>
        public static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Arrival location.
        /// </summary>
        public static string ArrivalLocation {
            get {
                return ResourceManager.GetString("ArrivalLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ATA.
        /// </summary>
        public static string ATA {
            get {
                return ResourceManager.GetString("ATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ATD.
        /// </summary>
        public static string ATD {
            get {
                return ResourceManager.GetString("ATD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Saving a docmapper.
        /// </summary>
        public static string BllAddNewDocument {
            get {
                return ResourceManager.GetString("BllAddNewDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Adding a new docmapper column.
        /// </summary>
        public static string BllAddNewDocumentColumn {
            get {
                return ResourceManager.GetString("BllAddNewDocumentColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Saving the docmapper has been completed successfully..
        /// </summary>
        public static string BllAddNewDocumentSuccess {
            get {
                return ResourceManager.GetString("BllAddNewDocumentSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loading containers.
        /// </summary>
        public static string BllDownloadContainers {
            get {
                return ResourceManager.GetString("BllDownloadContainers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The process of lot formation.
        /// </summary>
        public static string BllDownloadLot {
            get {
                return ResourceManager.GetString("BllDownloadLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loading the list of lots.
        /// </summary>
        public static string BllDownloadLots {
            get {
                return ResourceManager.GetString("BllDownloadLots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Uploading a tracing file.
        /// </summary>
        public static string BllExportAllTracing {
            get {
                return ResourceManager.GetString("BllExportAllTracing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Document filtering.
        /// </summary>
        public static string BllFilterDocuments {
            get {
                return ResourceManager.GetString("BllFilterDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loading columns available for a docmapper.
        /// </summary>
        public static string BllGetAllDocumentColumns {
            get {
                return ResourceManager.GetString("BllGetAllDocumentColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Receiving a document.
        /// </summary>
        public static string BllGetDocument {
            get {
                return ResourceManager.GetString("BllGetDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loading process steps.
        /// </summary>
        public static string BllGetProcessSteps {
            get {
                return ResourceManager.GetString("BllGetProcessSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loading parts for the container.
        /// </summary>
        public static string BllLoadPartsForContainer {
            get {
                return ResourceManager.GetString("BllLoadPartsForContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loading static data.
        /// </summary>
        public static string BllLoadStaticData {
            get {
                return ResourceManager.GetString("BllLoadStaticData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Updating the docmapper.
        /// </summary>
        public static string BllUpdateDocument {
            get {
                return ResourceManager.GetString("BllUpdateDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Docmapper update completed successfully.
        /// </summary>
        public static string BllUpdateDocumentSuccess {
            get {
                return ResourceManager.GetString("BllUpdateDocumentSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The process of loading the lot.
        /// </summary>
        public static string BllUploadLot {
            get {
                return ResourceManager.GetString("BllUploadLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Validation of document columns.
        /// </summary>
        public static string BllValidationFileColumns {
            get {
                return ResourceManager.GetString("BllValidationFileColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Carrier.
        /// </summary>
        public static string CarrierName {
            get {
                return ResourceManager.GetString("CarrierName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Case number.
        /// </summary>
        public static string CaseNumber {
            get {
                return ResourceManager.GetString("CaseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close date.
        /// </summary>
        public static string CloseDate {
            get {
                return ResourceManager.GetString("CloseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на completed.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Container.
        /// </summary>
        public static string Container {
            get {
                return ResourceManager.GetString("Container", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Container type.
        /// </summary>
        public static string ContainerType {
            get {
                return ResourceManager.GetString("ContainerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Customs location.
        /// </summary>
        public static string CustomsLocation {
            get {
                return ResourceManager.GetString("CustomsLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DefaultIcon.png.
        /// </summary>
        public static string DefaultAvatar {
            get {
                return ResourceManager.GetString("DefaultAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Default folder.
        /// </summary>
        public static string DefaultFolder {
            get {
                return ResourceManager.GetString("DefaultFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lot list.
        /// </summary>
        public static string DeliveryPageTitle {
            get {
                return ResourceManager.GetString("DeliveryPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delivery term.
        /// </summary>
        public static string DeliveryTerm {
            get {
                return ResourceManager.GetString("DeliveryTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Departure location.
        /// </summary>
        public static string DepartureLocation {
            get {
                return ResourceManager.GetString("DepartureLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Element name.
        /// </summary>
        public static string DocumentColumnElementName {
            get {
                return ResourceManager.GetString("DocumentColumnElementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Column number.
        /// </summary>
        public static string DocumentColumnNumber {
            get {
                return ResourceManager.GetString("DocumentColumnNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на System name.
        /// </summary>
        public static string DocumentColumnSystemColumnName {
            get {
                return ResourceManager.GetString("DocumentColumnSystemColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Docmapper name.
        /// </summary>
        public static string DocumentName {
            get {
                return ResourceManager.GetString("DocumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New content element.
        /// </summary>
        public static string DocumentNewContent {
            get {
                return ResourceManager.GetString("DocumentNewContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Here you can add a new content element..
        /// </summary>
        public static string DocumentNewContentTitle {
            get {
                return ResourceManager.GetString("DocumentNewContentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Row number.
        /// </summary>
        public static string DocumentRowNumber {
            get {
                return ResourceManager.GetString("DocumentRowNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add a new template.
        /// </summary>
        public static string DocumentTooltip {
            get {
                return ResourceManager.GetString("DocumentTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Editing a lot.
        /// </summary>
        public static string EditDeliveryPageTitle {
            get {
                return ResourceManager.GetString("EditDeliveryPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ETA.
        /// </summary>
        public static string ETA {
            get {
                return ResourceManager.GetString("ETA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ETD.
        /// </summary>
        public static string ETD {
            get {
                return ResourceManager.GetString("ETD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на First data row.
        /// </summary>
        public static string FirstDataRow {
            get {
                return ResourceManager.GetString("FirstDataRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Gross weight.
        /// </summary>
        public static string GrossWeight {
            get {
                return ResourceManager.GetString("GrossWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IMO.
        /// </summary>
        public static string IMO {
            get {
                return ResourceManager.GetString("IMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invoice number.
        /// </summary>
        public static string InvoiceNumber {
            get {
                return ResourceManager.GetString("InvoiceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Containers list.
        /// </summary>
        public static string ListOfContainers {
            get {
                return ResourceManager.GetString("ListOfContainers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на access denied.
        /// </summary>
        public static string LogAccessDenied {
            get {
                return ResourceManager.GetString("LogAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на saving a new docmapper.
        /// </summary>
        public static string LogAddNewDocument {
            get {
                return ResourceManager.GetString("LogAddNewDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на adding a docmapper column &apos;{0}&apos;.
        /// </summary>
        public static string LogDocmapperColumnAdd {
            get {
                return ResourceManager.GetString("LogDocmapperColumnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на getting columns that can be added to the document.
        /// </summary>
        public static string LogDocmapperColumnGet {
            get {
                return ResourceManager.GetString("LogDocmapperColumnGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на adding a new document content.
        /// </summary>
        public static string LogDocmapperContentAdd {
            get {
                return ResourceManager.GetString("LogDocmapperContentAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на filtering documents by search text &apos;{0}&apos;.
        /// </summary>
        public static string LogDocmapperFilter {
            get {
                return ResourceManager.GetString("LogDocmapperFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на getting the document with id &apos;{0}&apos;.
        /// </summary>
        public static string LogDocmapperGetById {
            get {
                return ResourceManager.GetString("LogDocmapperGetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на activity status of the document has been switched to &apos;{0}&apos;.
        /// </summary>
        public static string LogDocumentSwitchIsActive {
            get {
                return ResourceManager.GetString("LogDocumentSwitchIsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на receiving lots.
        /// </summary>
        public static string LogDownloadLots {
            get {
                return ResourceManager.GetString("LogDownloadLots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на starting export a file {0}.
        /// </summary>
        public static string LogExportFile {
            get {
                return ResourceManager.GetString("LogExportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на filtering the list with transport with transport name &apos;{0}&apos;.
        /// </summary>
        public static string LogFilterTransport {
            get {
                return ResourceManager.GetString("LogFilterTransport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на beginning of the formation of the path to the file with errors based on the path: &apos;{0}&apos;.
        /// </summary>
        public static string LogFormationNgFolder {
            get {
                return ResourceManager.GetString("LogFormationNgFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на loading containers for the lot with uniq id &apos;{0}&apos;.
        /// </summary>
        public static string LogGetContainersByLotId {
            get {
                return ResourceManager.GetString("LogGetContainersByLotId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на loading parts for the container with uniq id &apos;{0}&apos;.
        /// </summary>
        public static string LogGetPartsForContainer {
            get {
                return ResourceManager.GetString("LogGetPartsForContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login.
        /// </summary>
        public static string LogInButton {
            get {
                return ResourceManager.GetString("LogInButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Authorization.
        /// </summary>
        public static string LogInPageTitle {
            get {
                return ResourceManager.GetString("LogInPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на loading static data.
        /// </summary>
        public static string LogLoadStaticData {
            get {
                return ResourceManager.GetString("LogLoadStaticData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на loading lot with uniq id &apos;{0}&apos;.
        /// </summary>
        public static string LogLotGetById {
            get {
                return ResourceManager.GetString("LogLotGetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на getting orders for the shipper with uniq id &apos;{0}&apos;.
        /// </summary>
        public static string LogOrdersGetForShipper {
            get {
                return ResourceManager.GetString("LogOrdersGetForShipper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на receiving the steps of operations &apos;{0}&apos; for the current user by his section.
        /// </summary>
        public static string LogProcessStepsGet {
            get {
                return ResourceManager.GetString("LogProcessStepsGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на redirecting to the lot editing page.
        /// </summary>
        public static string LogRedirectToEditingLot {
            get {
                return ResourceManager.GetString("LogRedirectToEditingLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на adding the new transport &apos;{0}&apos;.
        /// </summary>
        public static string LogTransportAdd {
            get {
                return ResourceManager.GetString("LogTransportAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на updating a docmapper with id &apos;{0}&apos;.
        /// </summary>
        public static string LogUpdateDocument {
            get {
                return ResourceManager.GetString("LogUpdateDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на updating filters to represent containers.
        /// </summary>
        public static string LogUpdatingFiltersForContainers {
            get {
                return ResourceManager.GetString("LogUpdatingFiltersForContainers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на updating filters to represent details.
        /// </summary>
        public static string LogUpdatingFiltersForDetails {
            get {
                return ResourceManager.GetString("LogUpdatingFiltersForDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на lot formation.
        /// </summary>
        public static string LogUploadLot {
            get {
                return ResourceManager.GetString("LogUploadLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на lot with a unique id &apos;{0}&apos; has been formed.
        /// </summary>
        public static string LogUploadLotCompleted {
            get {
                return ResourceManager.GetString("LogUploadLotCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на apply filters to represent containers.
        /// </summary>
        public static string LogUpplyFiltersForContainers {
            get {
                return ResourceManager.GetString("LogUpplyFiltersForContainers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на apply filters to represent details.
        /// </summary>
        public static string LogUpplyFiltersForDetails {
            get {
                return ResourceManager.GetString("LogUpplyFiltersForDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на getting user.
        /// </summary>
        public static string LogUserGet {
            get {
                return ResourceManager.GetString("LogUserGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на nformation for user updated: &apos;{0}&apos;.
        /// </summary>
        public static string LogUserUpdated {
            get {
                return ResourceManager.GetString("LogUserUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на validating a file headers {0}.
        /// </summary>
        public static string LogValidatingHeaders {
            get {
                return ResourceManager.GetString("LogValidatingHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на value validation: &apos;{0}&apos; in column &apos;{1}&apos;.
        /// </summary>
        public static string LogValueValidation {
            get {
                return ResourceManager.GetString("LogValueValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на validation in column &apos;{0}&apos; completed with warning: &apos;{1}&apos;.
        /// </summary>
        public static string LogValueValidationWarning {
            get {
                return ResourceManager.GetString("LogValueValidationWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на with result &apos;{0}&apos;.
        /// </summary>
        public static string LogWithResult {
            get {
                return ResourceManager.GetString("LogWithResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lot number.
        /// </summary>
        public static string LotNumber {
            get {
                return ResourceManager.GetString("LotNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lot order.
        /// </summary>
        public static string LotOrder {
            get {
                return ResourceManager.GetString("LotOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на If there are no orders in the list, try to select the shipper first..
        /// </summary>
        public static string LotOrderToolTip {
            get {
                return ResourceManager.GetString("LotOrderToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Home page.
        /// </summary>
        public static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File Upload Wizard.
        /// </summary>
        public static string MasterExportFile {
            get {
                return ResourceManager.GetString("MasterExportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File Upload Wizard.
        /// </summary>
        public static string MasterUploadFile {
            get {
                return ResourceManager.GetString("MasterUploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Net weight.
        /// </summary>
        public static string NetWeight {
            get {
                return ResourceManager.GetString("NetWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Adding a lot.
        /// </summary>
        public static string NewDeliveryPageTitle {
            get {
                return ResourceManager.GetString("NewDeliveryPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на NG-{0}-{1}{2}.
        /// </summary>
        public static string NgFileName {
            get {
                return ResourceManager.GetString("NgFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Packing type.
        /// </summary>
        public static string PackingType {
            get {
                return ResourceManager.GetString("PackingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Part name eng.
        /// </summary>
        public static string PartNameEng {
            get {
                return ResourceManager.GetString("PartNameEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Part number.
        /// </summary>
        public static string PartNumber {
            get {
                return ResourceManager.GetString("PartNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please press &apos;{0}&apos; to complete.
        /// </summary>
        public static string PleasePress {
            get {
                return ResourceManager.GetString("PleasePress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Position.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Quantity containers.
        /// </summary>
        public static string QuantityContainers {
            get {
                return ResourceManager.GetString("QuantityContainers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Seal number.
        /// </summary>
        public static string SealNumber {
            get {
                return ResourceManager.GetString("SealNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language settings.
        /// </summary>
        public static string SettingsLanguageTitle {
            get {
                return ResourceManager.GetString("SettingsLanguageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Production Supply System - this is app....
        /// </summary>
        public static string SettingsPageAboutText {
            get {
                return ResourceManager.GetString("SettingsPageAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About the app.
        /// </summary>
        public static string SettingsPageAboutTitle {
            get {
                return ResourceManager.GetString("SettingsPageAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The color of the design.
        /// </summary>
        public static string SettingsPageChooseThemeText {
            get {
                return ResourceManager.GetString("SettingsPageChooseThemeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Log out.
        /// </summary>
        public static string SettingsPageLogOutButtonText {
            get {
                return ResourceManager.GetString("SettingsPageLogOutButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Design settings.
        /// </summary>
        public static string SettingsPagePersonalizationTitle {
            get {
                return ResourceManager.GetString("SettingsPagePersonalizationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dark.
        /// </summary>
        public static string SettingsPageRadioButtonDarkTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Light.
        /// </summary>
        public static string SettingsPageRadioButtonLightTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Standard from Windows.
        /// </summary>
        public static string SettingsPageRadioButtonWindowsDefaultTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonWindowsDefaultTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на English.
        /// </summary>
        public static string SettingsPageRadioEnLanguage {
            get {
                return ResourceManager.GetString("SettingsPageRadioEnLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Russian.
        /// </summary>
        public static string SettingsPageRadioRuLanguage {
            get {
                return ResourceManager.GetString("SettingsPageRadioRuLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Theme color.
        /// </summary>
        public static string SettingsPageThemeColor {
            get {
                return ResourceManager.GetString("SettingsPageThemeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About user.
        /// </summary>
        public static string SettingsPageUserTitle {
            get {
                return ResourceManager.GetString("SettingsPageUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sheet name.
        /// </summary>
        public static string SheetName {
            get {
                return ResourceManager.GetString("SheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Active.
        /// </summary>
        public static string ShellActive {
            get {
                return ResourceManager.GetString("ShellActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add.
        /// </summary>
        public static string ShellAdd {
            get {
                return ResourceManager.GetString("ShellAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string ShellCancelButton {
            get {
                return ResourceManager.GetString("ShellCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Switching the language.
        /// </summary>
        public static string ShellChangeLanguage {
            get {
                return ResourceManager.GetString("ShellChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close.
        /// </summary>
        public static string ShellClose {
            get {
                return ResourceManager.GetString("ShellClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        public static string ShellDelete {
            get {
                return ResourceManager.GetString("ShellDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lot list.
        /// </summary>
        public static string ShellDeliveryPage {
            get {
                return ResourceManager.GetString("ShellDeliveryPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Details.
        /// </summary>
        public static string ShellDetails {
            get {
                return ResourceManager.GetString("ShellDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Changing the docmapper.
        /// </summary>
        public static string ShellDocumentMapperEditPage {
            get {
                return ResourceManager.GetString("ShellDocumentMapperEditPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Adding a new docmapper.
        /// </summary>
        public static string ShellDocumentMapperNewPage {
            get {
                return ResourceManager.GetString("ShellDocumentMapperNewPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Managing docmappers.
        /// </summary>
        public static string ShellDocumentMapperPage {
            get {
                return ResourceManager.GetString("ShellDocumentMapperPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit.
        /// </summary>
        public static string ShellEdit {
            get {
                return ResourceManager.GetString("ShellEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Editing a lot.
        /// </summary>
        public static string ShellEditDeliveryPage {
            get {
                return ResourceManager.GetString("ShellEditDeliveryPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The list of lots is empty. Click on the &apos;Upload Lot List&apos; button to update the list..
        /// </summary>
        public static string ShellEmptyLotList {
            get {
                return ResourceManager.GetString("ShellEmptyLotList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        public static string ShellError {
            get {
                return ResourceManager.GetString("ShellError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Files export complete.
        /// </summary>
        public static string ShellExportFileCompleted {
            get {
                return ResourceManager.GetString("ShellExportFileCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exporting files.
        /// </summary>
        public static string ShellExportFiles {
            get {
                return ResourceManager.GetString("ShellExportFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File name.
        /// </summary>
        public static string ShellFileName {
            get {
                return ResourceManager.GetString("ShellFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Go back.
        /// </summary>
        public static string ShellGoBackButton {
            get {
                return ResourceManager.GetString("ShellGoBackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open or close navigation.
        /// </summary>
        public static string ShellHamburgerButtonName {
            get {
                return ResourceManager.GetString("ShellHamburgerButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Home.
        /// </summary>
        public static string ShellMainPage {
            get {
                return ResourceManager.GetString("ShellMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To display the selected language correctly, you need to restart the application.
        /// </summary>
        public static string ShellMessageChangeLanguage {
            get {
                return ResourceManager.GetString("ShellMessageChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Adding a lot.
        /// </summary>
        public static string ShellNewDeliveryPage {
            get {
                return ResourceManager.GetString("ShellNewDeliveryPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not active.
        /// </summary>
        public static string ShellNoActive {
            get {
                return ResourceManager.GetString("ShellNoActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You do not have the necessary rights to perform this process.
        /// </summary>
        public static string ShellProcessForbidden {
            get {
                return ResourceManager.GetString("ShellProcessForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        public static string ShellSaveButton {
            get {
                return ResourceManager.GetString("ShellSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search.
        /// </summary>
        public static string ShellSearch {
            get {
                return ResourceManager.GetString("ShellSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select a date.
        /// </summary>
        public static string ShellSelectDate {
            get {
                return ResourceManager.GetString("ShellSelectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Total quantity.
        /// </summary>
        public static string ShellTotalQuantity {
            get {
                return ResourceManager.GetString("ShellTotalQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download.
        /// </summary>
        public static string ShellUploadButton {
            get {
                return ResourceManager.GetString("ShellUploadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The download has been completed successfully..
        /// </summary>
        public static string ShellUploadSuccess {
            get {
                return ResourceManager.GetString("ShellUploadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Use.
        /// </summary>
        public static string ShellUse {
            get {
                return ResourceManager.GetString("ShellUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please wait....
        /// </summary>
        public static string ShellWait {
            get {
                return ResourceManager.GetString("ShellWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .xlsx.
        /// </summary>
        public static string ShellXLSX {
            get {
                return ResourceManager.GetString("ShellXLSX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shipper.
        /// </summary>
        public static string ShipperName {
            get {
                return ResourceManager.GetString("ShipperName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Authorization error.
        /// </summary>
        public static string StatusLoginFails {
            get {
                return ResourceManager.GetString("StatusLoginFails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на There is no connection to the database.
        /// </summary>
        public static string StatusNotConnectionToDb {
            get {
                return ResourceManager.GetString("StatusNotConnectionToDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not authorized.
        /// </summary>
        public static string StatusUnauthorized {
            get {
                return ResourceManager.GetString("StatusUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An unexpected mistake.
        /// </summary>
        public static string StatusUnknownError {
            get {
                return ResourceManager.GetString("StatusUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на List of parts for container .
        /// </summary>
        public static string TitlePartsForContainer {
            get {
                return ResourceManager.GetString("TitlePartsForContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Transport document.
        /// </summary>
        public static string TransportDocument {
            get {
                return ResourceManager.GetString("TransportDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Transport name.
        /// </summary>
        public static string TransportName {
            get {
                return ResourceManager.GetString("TransportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Transport type.
        /// </summary>
        public static string TransportType {
            get {
                return ResourceManager.GetString("TransportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Document validation.
        /// </summary>
        public static string ValidationPageTitle {
            get {
                return ResourceManager.GetString("ValidationPageTitle", resourceCulture);
            }
        }
    }
}
