//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI_Interface.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UI_Interface.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Production Supply System.
        /// </summary>
        public static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Место прибытия лота.
        /// </summary>
        public static string ArrivalLocation {
            get {
                return ResourceManager.GetString("ArrivalLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фактическая дата прибытия.
        /// </summary>
        public static string ATA {
            get {
                return ResourceManager.GetString("ATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фактическая дата доставки.
        /// </summary>
        public static string ATD {
            get {
                return ResourceManager.GetString("ATD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранение документа.
        /// </summary>
        public static string BllAddNewDocument {
            get {
                return ResourceManager.GetString("BllAddNewDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавление новой колонки.
        /// </summary>
        public static string BllAddNewDocumentColumn {
            get {
                return ResourceManager.GetString("BllAddNewDocumentColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранение документа успешно завершено.
        /// </summary>
        public static string BllAddNewDocumentSuccess {
            get {
                return ResourceManager.GetString("BllAddNewDocumentSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузка контейнеров.
        /// </summary>
        public static string BllDownloadContainers {
            get {
                return ResourceManager.GetString("BllDownloadContainers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Процесс формирования лота.
        /// </summary>
        public static string BllDownloadLot {
            get {
                return ResourceManager.GetString("BllDownloadLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузка списка лотов.
        /// </summary>
        public static string BllDownloadLots {
            get {
                return ResourceManager.GetString("BllDownloadLots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выгрузка файла трейсинга.
        /// </summary>
        public static string BllExportAllTracing {
            get {
                return ResourceManager.GetString("BllExportAllTracing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фильтрация документов.
        /// </summary>
        public static string BllFilterDocuments {
            get {
                return ResourceManager.GetString("BllFilterDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузка колонок доступных для документа.
        /// </summary>
        public static string BllGetAllDocumentColumns {
            get {
                return ResourceManager.GetString("BllGetAllDocumentColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Получение документа.
        /// </summary>
        public static string BllGetDocument {
            get {
                return ResourceManager.GetString("BllGetDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузка шагов процесса.
        /// </summary>
        public static string BllGetProcessSteps {
            get {
                return ResourceManager.GetString("BllGetProcessSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузка деталей для контейнера.
        /// </summary>
        public static string BllLoadPartsForContainer {
            get {
                return ResourceManager.GetString("BllLoadPartsForContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузка статических данных.
        /// </summary>
        public static string BllLoadStaticData {
            get {
                return ResourceManager.GetString("BllLoadStaticData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновление документа.
        /// </summary>
        public static string BllUpdateDocument {
            get {
                return ResourceManager.GetString("BllUpdateDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновление документа успешно завершено.
        /// </summary>
        public static string BllUpdateDocumentSuccess {
            get {
                return ResourceManager.GetString("BllUpdateDocumentSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Процесс загрузки лота.
        /// </summary>
        public static string BllUploadLot {
            get {
                return ResourceManager.GetString("BllUploadLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Валидация колонок документа.
        /// </summary>
        public static string BllValidationFileColumns {
            get {
                return ResourceManager.GetString("BllValidationFileColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перевозчик.
        /// </summary>
        public static string CarrierName {
            get {
                return ResourceManager.GetString("CarrierName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер кейса.
        /// </summary>
        public static string CaseNumber {
            get {
                return ResourceManager.GetString("CaseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата закрытия лота.
        /// </summary>
        public static string CloseDate {
            get {
                return ResourceManager.GetString("CloseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Комментарий.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контейнер.
        /// </summary>
        public static string Container {
            get {
                return ResourceManager.GetString("Container", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип контейнера.
        /// </summary>
        public static string ContainerType {
            get {
                return ResourceManager.GetString("ContainerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Таможенный терминал.
        /// </summary>
        public static string CustomsLocation {
            get {
                return ResourceManager.GetString("CustomsLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DefaultIcon.png.
        /// </summary>
        public static string DefaultAvatar {
            get {
                return ResourceManager.GetString("DefaultAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Папка по умолчанию.
        /// </summary>
        public static string DefaultFolder {
            get {
                return ResourceManager.GetString("DefaultFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Журнал лотов.
        /// </summary>
        public static string DeliveryPageTitle {
            get {
                return ResourceManager.GetString("DeliveryPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Условия поставки.
        /// </summary>
        public static string DeliveryTerm {
            get {
                return ResourceManager.GetString("DeliveryTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Место отправления лота.
        /// </summary>
        public static string DepartureLocation {
            get {
                return ResourceManager.GetString("DepartureLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название колонки.
        /// </summary>
        public static string DocumentColumnElementName {
            get {
                return ResourceManager.GetString("DocumentColumnElementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер колонки.
        /// </summary>
        public static string DocumentColumnNumber {
            get {
                return ResourceManager.GetString("DocumentColumnNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Системное название.
        /// </summary>
        public static string DocumentColumnSystemColumnName {
            get {
                return ResourceManager.GetString("DocumentColumnSystemColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя шаблона.
        /// </summary>
        public static string DocumentName {
            get {
                return ResourceManager.GetString("DocumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новый элемент контента.
        /// </summary>
        public static string DocumentNewContent {
            get {
                return ResourceManager.GetString("DocumentNewContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тут вы можете добавить новый элемент контента..
        /// </summary>
        public static string DocumentNewContentTitle {
            get {
                return ResourceManager.GetString("DocumentNewContentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер строки.
        /// </summary>
        public static string DocumentRowNumber {
            get {
                return ResourceManager.GetString("DocumentRowNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить новый шаблон.
        /// </summary>
        public static string DocumentTooltip {
            get {
                return ResourceManager.GetString("DocumentTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактирование лота.
        /// </summary>
        public static string EditDeliveryPageTitle {
            get {
                return ResourceManager.GetString("EditDeliveryPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ожидаемая дата прибытия.
        /// </summary>
        public static string ETA {
            get {
                return ResourceManager.GetString("ETA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ожидаемая дата доставки.
        /// </summary>
        public static string ETD {
            get {
                return ResourceManager.GetString("ETD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фильтр.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер строки с которой начинаются данные.
        /// </summary>
        public static string FirstDataRow {
            get {
                return ResourceManager.GetString("FirstDataRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вес брутто.
        /// </summary>
        public static string GrossWeight {
            get {
                return ResourceManager.GetString("GrossWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Признак опасности груза.
        /// </summary>
        public static string IMO {
            get {
                return ResourceManager.GetString("IMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер счета.
        /// </summary>
        public static string InvoiceNumber {
            get {
                return ResourceManager.GetString("InvoiceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список контейнеров.
        /// </summary>
        public static string ListOfContainers {
            get {
                return ResourceManager.GetString("ListOfContainers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вход.
        /// </summary>
        public static string LogInButton {
            get {
                return ResourceManager.GetString("LogInButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Авторизация.
        /// </summary>
        public static string LogInPageTitle {
            get {
                return ResourceManager.GetString("LogInPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер лота.
        /// </summary>
        public static string LotNumber {
            get {
                return ResourceManager.GetString("LotNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заказ лота.
        /// </summary>
        public static string LotOrder {
            get {
                return ResourceManager.GetString("LotOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Если заказов нет в списке, попробуйте сначала выбрать отправителя..
        /// </summary>
        public static string LotOrderToolTip {
            get {
                return ResourceManager.GetString("LotOrderToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Главная страница.
        /// </summary>
        public static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мастер загрузки файлов.
        /// </summary>
        public static string MasterUploadFile {
            get {
                return ResourceManager.GetString("MasterUploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вес нетто.
        /// </summary>
        public static string NetWeight {
            get {
                return ResourceManager.GetString("NetWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавление лота.
        /// </summary>
        public static string NewDeliveryPageTitle {
            get {
                return ResourceManager.GetString("NewDeliveryPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип упаковки.
        /// </summary>
        public static string PackingType {
            get {
                return ResourceManager.GetString("PackingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Английское имя детали.
        /// </summary>
        public static string PartNameEng {
            get {
                return ResourceManager.GetString("PartNameEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер детали.
        /// </summary>
        public static string PartNumber {
            get {
                return ResourceManager.GetString("PartNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Позиция.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Колличество.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Колличество контейнеров.
        /// </summary>
        public static string QuantityContainers {
            get {
                return ResourceManager.GetString("QuantityContainers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер пломбы.
        /// </summary>
        public static string SealNumber {
            get {
                return ResourceManager.GetString("SealNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Production Supply System - это приложение....
        /// </summary>
        public static string SettingsPageAboutText {
            get {
                return ResourceManager.GetString("SettingsPageAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на О приложении.
        /// </summary>
        public static string SettingsPageAboutTitle {
            get {
                return ResourceManager.GetString("SettingsPageAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цвет оформления.
        /// </summary>
        public static string SettingsPageChooseThemeText {
            get {
                return ResourceManager.GetString("SettingsPageChooseThemeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выйти.
        /// </summary>
        public static string SettingsPageLogOutButtonText {
            get {
                return ResourceManager.GetString("SettingsPageLogOutButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки оформления.
        /// </summary>
        public static string SettingsPagePersonalizationTitle {
            get {
                return ResourceManager.GetString("SettingsPagePersonalizationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тёмная.
        /// </summary>
        public static string SettingsPageRadioButtonDarkTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Светлая.
        /// </summary>
        public static string SettingsPageRadioButtonLightTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стандартная из Windows.
        /// </summary>
        public static string SettingsPageRadioButtonWindowsDefaultTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonWindowsDefaultTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на О пользователе.
        /// </summary>
        public static string SettingsPageUserTitle {
            get {
                return ResourceManager.GetString("SettingsPageUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название листа.
        /// </summary>
        public static string SheetName {
            get {
                return ResourceManager.GetString("SheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Активен.
        /// </summary>
        public static string ShellActive {
            get {
                return ResourceManager.GetString("ShellActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить.
        /// </summary>
        public static string ShellAdd {
            get {
                return ResourceManager.GetString("ShellAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отменить.
        /// </summary>
        public static string ShellCancelButton {
            get {
                return ResourceManager.GetString("ShellCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закрыть.
        /// </summary>
        public static string ShellClose {
            get {
                return ResourceManager.GetString("ShellClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        public static string ShellDelete {
            get {
                return ResourceManager.GetString("ShellDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Журнал лотов.
        /// </summary>
        public static string ShellDeliveryPage {
            get {
                return ResourceManager.GetString("ShellDeliveryPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Общая информация.
        /// </summary>
        public static string ShellDetails {
            get {
                return ResourceManager.GetString("ShellDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменение шаблона.
        /// </summary>
        public static string ShellDocumentMapperEditPage {
            get {
                return ResourceManager.GetString("ShellDocumentMapperEditPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавление нового шаблона.
        /// </summary>
        public static string ShellDocumentMapperNewPage {
            get {
                return ResourceManager.GetString("ShellDocumentMapperNewPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Управление шаблонами.
        /// </summary>
        public static string ShellDocumentMapperPage {
            get {
                return ResourceManager.GetString("ShellDocumentMapperPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактировать.
        /// </summary>
        public static string ShellEdit {
            get {
                return ResourceManager.GetString("ShellEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактирование лота.
        /// </summary>
        public static string ShellEditDeliveryPage {
            get {
                return ResourceManager.GetString("ShellEditDeliveryPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список лотов пуст. Нажмите на кнопку &apos;Подгрузить список лотов&apos; для обновления списка..
        /// </summary>
        public static string ShellEmptyLotList {
            get {
                return ResourceManager.GetString("ShellEmptyLotList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        public static string ShellError {
            get {
                return ResourceManager.GetString("ShellError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя файла.
        /// </summary>
        public static string ShellFileName {
            get {
                return ResourceManager.GetString("ShellFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Go back.
        /// </summary>
        public static string ShellGoBackButton {
            get {
                return ResourceManager.GetString("ShellGoBackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open or close navigation.
        /// </summary>
        public static string ShellHamburgerButtonName {
            get {
                return ResourceManager.GetString("ShellHamburgerButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Главная.
        /// </summary>
        public static string ShellMainPage {
            get {
                return ResourceManager.GetString("ShellMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавление лота.
        /// </summary>
        public static string ShellNewDeliveryPage {
            get {
                return ResourceManager.GetString("ShellNewDeliveryPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не активен.
        /// </summary>
        public static string ShellNoActive {
            get {
                return ResourceManager.GetString("ShellNoActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы не обладаете необходимыми правами для выполнения этого процесса.
        /// </summary>
        public static string ShellProcessForbidden {
            get {
                return ResourceManager.GetString("ShellProcessForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить.
        /// </summary>
        public static string ShellSaveButton {
            get {
                return ResourceManager.GetString("ShellSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск.
        /// </summary>
        public static string ShellSearch {
            get {
                return ResourceManager.GetString("ShellSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите дату.
        /// </summary>
        public static string ShellSelectDate {
            get {
                return ResourceManager.GetString("ShellSelectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузить.
        /// </summary>
        public static string ShellUploadButton {
            get {
                return ResourceManager.GetString("ShellUploadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузка успешно завершена. .
        /// </summary>
        public static string ShellUploadSuccess {
            get {
                return ResourceManager.GetString("ShellUploadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Использовать.
        /// </summary>
        public static string ShellUse {
            get {
                return ResourceManager.GetString("ShellUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пожалуйста подождите....
        /// </summary>
        public static string ShellWait {
            get {
                return ResourceManager.GetString("ShellWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправитель.
        /// </summary>
        public static string ShipperName {
            get {
                return ResourceManager.GetString("ShipperName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка авторизации.
        /// </summary>
        public static string StatusLoginFails {
            get {
                return ResourceManager.GetString("StatusLoginFails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет соединения с базой данных.
        /// </summary>
        public static string StatusNotConnectionToDb {
            get {
                return ResourceManager.GetString("StatusNotConnectionToDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не авторизован.
        /// </summary>
        public static string StatusUnauthorized {
            get {
                return ResourceManager.GetString("StatusUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не предвиденная ошибка.
        /// </summary>
        public static string StatusUnknownError {
            get {
                return ResourceManager.GetString("StatusUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список деталей для контейнера .
        /// </summary>
        public static string TitlePartsForContainer {
            get {
                return ResourceManager.GetString("TitlePartsForContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Документ транспорта.
        /// </summary>
        public static string TransportDocument {
            get {
                return ResourceManager.GetString("TransportDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название транспорта.
        /// </summary>
        public static string TransportName {
            get {
                return ResourceManager.GetString("TransportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип перевозки.
        /// </summary>
        public static string TransportType {
            get {
                return ResourceManager.GetString("TransportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Валидация документа.
        /// </summary>
        public static string ValidationPageTitle {
            get {
                return ResourceManager.GetString("ValidationPageTitle", resourceCulture);
            }
        }
    }
}
