// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using production_supply_system.EntityFramework.DAL.Models.CustomsSchema;
using production_supply_system.EntityFramework.DAL.Models.dboSchema;
using production_supply_system.EntityFramework.DAL.Models.DocmapperSchema;
using production_supply_system.EntityFramework.DAL.Models.InboundSchema;
using production_supply_system.EntityFramework.DAL.Models.MasterSchema;
using production_supply_system.EntityFramework.DAL.Models.PartscontrolSchema;
using production_supply_system.EntityFramework.DAL.Models.PlanningSchema;
using production_supply_system.EntityFramework.DAL.Models.UsersSchema;


namespace production_supply_system.EntityFramework.DAL.Models.MasterSchema;

[Table("tbd_Processes", Schema = "Master")]
public partial class Process
{
    [Key]
    [Column("Process_Id")]
    public int ProcessId { get; set; }

    [Column("Process_Name")]
    [StringLength(300)]
    public string ProcessName { get; set; } = null!;

    [InverseProperty("Process")]
    public virtual ICollection<ProcessesStep> ProcessesSteps { get; set; } = new List<ProcessesStep>();
}