// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using production_supply_system.EntityFramework.DAL.Models.CustomsSchema;
using production_supply_system.EntityFramework.DAL.Models.dboSchema;
using production_supply_system.EntityFramework.DAL.Models.DocmapperSchema;
using production_supply_system.EntityFramework.DAL.Models.InboundSchema;
using production_supply_system.EntityFramework.DAL.Models.MasterSchema;
using production_supply_system.EntityFramework.DAL.Models.PartscontrolSchema;
using production_supply_system.EntityFramework.DAL.Models.PlanningSchema;
using production_supply_system.EntityFramework.DAL.Models.UsersSchema;


namespace production_supply_system.EntityFramework.DAL.Models.PlanningSchema;

[Table("tbd_Statuses_For_SFS_Upload", Schema = "Planning")]
public partial class StatusesForSfsUpload
{
    [Key]
    [Column("Status_For_SFS_Upload_Id")]
    public int StatusForSfsUploadId { get; set; }

    [Column("Status_Name")]
    [StringLength(10)]
    public string StatusName { get; set; } = null!;

    [InverseProperty("StatusForSfsUpload")]
    public virtual ICollection<PlannedSequence> PlannedSequences { get; set; } = new List<PlannedSequence>();
}