// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using production_supply_system.EntityFramework.DAL.Models.CustomsSchema;
using production_supply_system.EntityFramework.DAL.Models.dboSchema;
using production_supply_system.EntityFramework.DAL.Models.DocmapperSchema;
using production_supply_system.EntityFramework.DAL.Models.InboundSchema;
using production_supply_system.EntityFramework.DAL.Models.MasterSchema;
using production_supply_system.EntityFramework.DAL.Models.PartscontrolSchema;
using production_supply_system.EntityFramework.DAL.Models.PlanningSchema;
using production_supply_system.EntityFramework.DAL.Models.UsersSchema;


namespace production_supply_system.EntityFramework.DAL.Models.PlanningSchema;

[Table("tbd_VINs_In_Container", Schema = "Planning")]
public partial class VinsInContainer
{
    [Key]
    [Column("VIN_In_Container_Id")]
    public int VinInContainerId { get; set; }

    [Column("Container_In_Lot_Id")]
    public int ContainerInLotId { get; set; }

    [Column("Supplier_VIN_Number")]
    [StringLength(50)]
    public string SupplierVinNumber { get; set; } = null!;

    [Column("Modvar_Id")]
    public int ModvarId { get; set; }

    [Column("Lot_Id")]
    public int LotId { get; set; }

    [ForeignKey("ContainerInLotId")]
    [InverseProperty("VinsInContainers")]
    public virtual ContainersInLot ContainerInLot { get; set; } = null!;

    [InverseProperty("VinInContainer")]
    public virtual BoundVin? BoundVin { get; set; }

    [InverseProperty("VinInContainer")]
    public virtual PlannedSequence? PlannedSequence { get; set; }
}