// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using production_supply_system.EntityFramework.DAL.TestContext.CustomsSchema;
using production_supply_system.EntityFramework.DAL.TestContext.dboSchema;
using production_supply_system.EntityFramework.DAL.TestContext.DocmapperSchema;
using production_supply_system.EntityFramework.DAL.TestContext.InboundSchema;
using production_supply_system.EntityFramework.DAL.TestContext.MasterSchema;
using production_supply_system.EntityFramework.DAL.TestContext.PartscontrolSchema;
using production_supply_system.EntityFramework.DAL.TestContext.PlanningSchema;
using production_supply_system.EntityFramework.DAL.TestContext.UsersSchema;


namespace production_supply_system.EntityFramework.DAL.TestContext.dboSchema;

[Table("tbd_History_Of_Changes")]
public partial class TbdHistoryOfChange
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [StringLength(50)]
    public string ObjectName { get; set; } = null!;

    public int RecordId { get; set; }

    [StringLength(50)]
    public string? FieldName { get; set; }

    [StringLength(150)]
    public string? OldValue { get; set; }

    [StringLength(150)]
    public string? NewValue { get; set; }

    [StringLength(7)]
    public string UserName { get; set; } = null!;

    [Column(TypeName = "datetime")]
    public DateTime? Added { get; set; }
}