// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using production_supply_system.EntityFramework.DAL.TestContext.CustomsSchema;
using production_supply_system.EntityFramework.DAL.TestContext.dboSchema;
using production_supply_system.EntityFramework.DAL.TestContext.DocmapperSchema;
using production_supply_system.EntityFramework.DAL.TestContext.InboundSchema;
using production_supply_system.EntityFramework.DAL.TestContext.MasterSchema;
using production_supply_system.EntityFramework.DAL.TestContext.PartscontrolSchema;
using production_supply_system.EntityFramework.DAL.TestContext.PlanningSchema;
using production_supply_system.EntityFramework.DAL.TestContext.UsersSchema;


namespace production_supply_system.EntityFramework.DAL.TestContext.dboSchema;

[Table("tbd_Sections")]
public partial class TbdSection
{
    [Key]
    [Column("Section_Id")]
    public int SectionId { get; set; }

    [Column("Section_Name")]
    [StringLength(300)]
    public string SectionName { get; set; } = null!;

    [InverseProperty("Section")]
    public virtual ICollection<TbdProcessesStep> TbdProcessesSteps { get; set; } = new List<TbdProcessesStep>();

    [InverseProperty("Section")]
    public virtual ICollection<TbdUser> TbdUsers { get; set; } = new List<TbdUser>();
}