// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using production_supply_system.EntityFramework.DAL.TestContext.CustomsSchema;
using production_supply_system.EntityFramework.DAL.TestContext.dboSchema;
using production_supply_system.EntityFramework.DAL.TestContext.DocmapperSchema;
using production_supply_system.EntityFramework.DAL.TestContext.InboundSchema;
using production_supply_system.EntityFramework.DAL.TestContext.MasterSchema;
using production_supply_system.EntityFramework.DAL.TestContext.PartscontrolSchema;
using production_supply_system.EntityFramework.DAL.TestContext.PlanningSchema;
using production_supply_system.EntityFramework.DAL.TestContext.UsersSchema;


namespace production_supply_system.EntityFramework.DAL.TestContext.PartscontrolSchema;

[Table("tbd_Purchase_Orders", Schema = "Partscontrol")]
[Index("PurchaseOrderNumber", Name = "IX_tbd_PurchaseOrders", IsUnique = true)]
public partial class TbdPurchaseOrder
{
    [Key]
    [Column("Purchase_Order_Id")]
    public int PurchaseOrderId { get; set; }

    [Column("Shipper_Id")]
    public int ShipperId { get; set; }

    [Column("Order_Type_Id")]
    public int OrderTypeId { get; set; }

    [Column("Purchase_Order_Number")]
    [StringLength(10)]
    public string PurchaseOrderNumber { get; set; } = null!;

    [Column("Purchase_Order_Date")]
    public DateOnly PurchaseOrderDate { get; set; }

    [ForeignKey("OrderTypeId")]
    [InverseProperty("TbdPurchaseOrders")]
    public virtual TbdTypesOfOrder OrderType { get; set; } = null!;

    [ForeignKey("ShipperId")]
    [InverseProperty("TbdPurchaseOrders")]
    public virtual TbdShipper Shipper { get; set; } = null!;

    [InverseProperty("PurchaseOrder")]
    public virtual ICollection<TbdInvoice> TbdInvoices { get; set; } = new List<TbdInvoice>();

    [InverseProperty("LotPurchaseOrder")]
    public virtual ICollection<TbdLot> TbdLots { get; set; } = new List<TbdLot>();
}