// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using production_supply_system.EntityFramework.DAL.TestContext.CustomsSchema;
using production_supply_system.EntityFramework.DAL.TestContext.dboSchema;
using production_supply_system.EntityFramework.DAL.TestContext.DocmapperSchema;
using production_supply_system.EntityFramework.DAL.TestContext.InboundSchema;
using production_supply_system.EntityFramework.DAL.TestContext.MasterSchema;
using production_supply_system.EntityFramework.DAL.TestContext.PartscontrolSchema;
using production_supply_system.EntityFramework.DAL.TestContext.PlanningSchema;
using production_supply_system.EntityFramework.DAL.TestContext.UsersSchema;


namespace production_supply_system.EntityFramework.DAL.TestContext.PartscontrolSchema;

[Table("tbd_Types_Of_Order", Schema = "Partscontrol")]
public partial class TbdTypesOfOrder
{
    [Key]
    [Column("Order_Type_Id")]
    public int OrderTypeId { get; set; }

    [Column("Order_Type")]
    [StringLength(10)]
    public string OrderType { get; set; } = null!;

    [InverseProperty("OrderType")]
    public virtual ICollection<TbdPurchaseOrder> TbdPurchaseOrders { get; set; } = new List<TbdPurchaseOrder>();
}