// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using production_supply_system.EntityFramework.DAL.TestContext;
using production_supply_system.EntityFramework.DAL.TestContext.CustomsSchema;
using production_supply_system.EntityFramework.DAL.TestContext.dboSchema;
using production_supply_system.EntityFramework.DAL.TestContext.DocmapperSchema;
using production_supply_system.EntityFramework.DAL.TestContext.InboundSchema;
using production_supply_system.EntityFramework.DAL.TestContext.MasterSchema;
using production_supply_system.EntityFramework.DAL.TestContext.PartscontrolSchema;
using production_supply_system.EntityFramework.DAL.TestContext.PlanningSchema;
using production_supply_system.EntityFramework.DAL.TestContext.UsersSchema;
using System;
using System.Collections.Generic;

#nullable disable

namespace production_supply_system.EntityFramework.DAL.TestContext.Configurations
{
    public partial class TbdCustomsPartConfiguration : IEntityTypeConfiguration<TbdCustomsPart>
    {
        public void Configure(EntityTypeBuilder<TbdCustomsPart> entity)
        {
            entity.HasKey(e => e.PartNumberId).HasName("PK_tbd_CustomsParts");

            entity.Property(e => e.PartNumberId).ValueGeneratedNever();
            entity.Property(e => e.DateAdd).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.PartType).WithMany(p => p.TbdCustomsParts)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tbd_CustomsParts_tbd_PartTypes");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TbdCustomsPart> entity);
    }
}
