// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using production_supply_system.EntityFramework.DAL.TestContext;
using production_supply_system.EntityFramework.DAL.TestContext.CustomsSchema;
using production_supply_system.EntityFramework.DAL.TestContext.dboSchema;
using production_supply_system.EntityFramework.DAL.TestContext.DocmapperSchema;
using production_supply_system.EntityFramework.DAL.TestContext.InboundSchema;
using production_supply_system.EntityFramework.DAL.TestContext.MasterSchema;
using production_supply_system.EntityFramework.DAL.TestContext.PartscontrolSchema;
using production_supply_system.EntityFramework.DAL.TestContext.PlanningSchema;
using production_supply_system.EntityFramework.DAL.TestContext.UsersSchema;
using System;
using System.Collections.Generic;

#nullable disable

namespace production_supply_system.EntityFramework.DAL.TestContext.Configurations
{
    public partial class TbdLotConfiguration : IEntityTypeConfiguration<TbdLot>
    {
        public void Configure(EntityTypeBuilder<TbdLot> entity)
        {
            entity.HasOne(d => d.Carrier).WithMany(p => p.TbdLots)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tbd_Lots_tbd_Carriers");

            entity.HasOne(d => d.DeliveryTerms).WithMany(p => p.TbdLots)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tbd_Lots_tbd_Delivery_Terms");

            entity.HasOne(d => d.LotArrivalLocation).WithMany(p => p.TbdLotLotArrivalLocations)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tbd_Lots_tbd_Locations1");

            entity.HasOne(d => d.LotCustomsLocation).WithMany(p => p.TbdLotLotCustomsLocations).HasConstraintName("FK_tbd_Lots_tbd_Locations2");

            entity.HasOne(d => d.LotDepartureLocation).WithMany(p => p.TbdLotLotDepartureLocations)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tbd_Lots_tbd_Locations");

            entity.HasOne(d => d.LotInvoice).WithMany(p => p.TbdLots)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tbd_Lots_tbd_Invoices");

            entity.HasOne(d => d.LotPurchaseOrder).WithMany(p => p.TbdLots)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tbd_Lots_tbd_PurchaseOrders");

            entity.HasOne(d => d.LotTransport).WithMany(p => p.TbdLots).HasConstraintName("FK_tbd_Lots_tbd_Transports");

            entity.HasOne(d => d.LotTransportType).WithMany(p => p.TbdLots)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tbd_Lots_tbd_Types_Of_Transport");

            entity.HasOne(d => d.Shipper).WithMany(p => p.TbdLots)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tbd_Lots_tbd_Shippers");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TbdLot> entity);
    }
}
