// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using production_supply_system.EntityFramework.DAL.TestContext;
using production_supply_system.EntityFramework.DAL.TestContext.CustomsSchema;
using production_supply_system.EntityFramework.DAL.TestContext.dboSchema;
using production_supply_system.EntityFramework.DAL.TestContext.DocmapperSchema;
using production_supply_system.EntityFramework.DAL.TestContext.InboundSchema;
using production_supply_system.EntityFramework.DAL.TestContext.MasterSchema;
using production_supply_system.EntityFramework.DAL.TestContext.PartscontrolSchema;
using production_supply_system.EntityFramework.DAL.TestContext.PlanningSchema;
using production_supply_system.EntityFramework.DAL.TestContext.UsersSchema;
using System;
using System.Collections.Generic;

#nullable disable

namespace production_supply_system.EntityFramework.DAL.TestContext.Configurations
{
    public partial class TbdPartsInInvoiceConfiguration : IEntityTypeConfiguration<TbdPartsInInvoice>
    {
        public void Configure(EntityTypeBuilder<TbdPartsInInvoice> entity)
        {
            entity.HasKey(e => e.PartInInvoiceId).HasName("PK_tbd_PartsInInvoice");

            entity.HasOne(d => d.Invoice).WithMany(p => p.TbdPartsInInvoices)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tbd_PartsInInvoice_tbd_Invoices1");

            entity.HasOne(d => d.PartNumber).WithMany(p => p.TbdPartsInInvoices)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tbd_PartsInInvoice_tbd_CustomsParts");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TbdPartsInInvoice> entity);
    }
}
