// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using production_supply_system.EntityFramework.DAL.TestContext;
using production_supply_system.EntityFramework.DAL.TestContext.CustomsSchema;
using production_supply_system.EntityFramework.DAL.TestContext.dboSchema;
using production_supply_system.EntityFramework.DAL.TestContext.DocmapperSchema;
using production_supply_system.EntityFramework.DAL.TestContext.InboundSchema;
using production_supply_system.EntityFramework.DAL.TestContext.MasterSchema;
using production_supply_system.EntityFramework.DAL.TestContext.PartscontrolSchema;
using production_supply_system.EntityFramework.DAL.TestContext.PlanningSchema;
using production_supply_system.EntityFramework.DAL.TestContext.UsersSchema;
using System;
using System.Collections.Generic;

#nullable disable

namespace production_supply_system.EntityFramework.DAL.TestContext.Configurations
{
    public partial class TbdPartsInContainerConfiguration : IEntityTypeConfiguration<TbdPartsInContainer>
    {
        public void Configure(EntityTypeBuilder<TbdPartsInContainer> entity)
        {
            entity.HasKey(e => e.PartInContainerId).HasName("PK_tbd_PartsInContainer");

            entity.HasOne(d => d.Case).WithMany(p => p.TbdPartsInContainers).HasConstraintName("FK_tbd_Parts_In_Container_tbd_Cases");

            entity.HasOne(d => d.ContainerInLot).WithMany(p => p.TbdPartsInContainers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tbd_PartsInContainer_tbd_ContainersInLot");

            entity.HasOne(d => d.PartInvoice).WithMany(p => p.TbdPartsInContainers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tbd_PartsInContainer_tbd_Invoices");

            entity.HasOne(d => d.PartNumber).WithMany(p => p.TbdPartsInContainers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tbd_PartsInContainer_tbd_CustomsParts");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TbdPartsInContainer> entity);
    }
}
