// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using production_supply_system.EntityFramework.DAL.TestContext;
using production_supply_system.EntityFramework.DAL.TestContext.CustomsSchema;
using production_supply_system.EntityFramework.DAL.TestContext.dboSchema;
using production_supply_system.EntityFramework.DAL.TestContext.DocmapperSchema;
using production_supply_system.EntityFramework.DAL.TestContext.InboundSchema;
using production_supply_system.EntityFramework.DAL.TestContext.MasterSchema;
using production_supply_system.EntityFramework.DAL.TestContext.PartscontrolSchema;
using production_supply_system.EntityFramework.DAL.TestContext.PlanningSchema;
using production_supply_system.EntityFramework.DAL.TestContext.UsersSchema;
using System;
using System.Collections.Generic;

#nullable disable

namespace production_supply_system.EntityFramework.DAL.TestContext.Configurations
{
    public partial class TbdPlannedSequenceConfiguration : IEntityTypeConfiguration<TbdPlannedSequence>
    {
        public void Configure(EntityTypeBuilder<TbdPlannedSequence> entity)
        {
            entity.Property(e => e.IsSuspicious).HasDefaultValue(0);
            entity.Property(e => e.IsUnyelding).HasDefaultValue(0);
            entity.Property(e => e.StatusForSfsUploadId).HasDefaultValue(1);

            entity.HasOne(d => d.StatusForSfsUpload).WithMany(p => p.TbdPlannedSequences).HasConstraintName("FK_tbd_PlannedSequence_tbd_StatusesForSFSUpload");

            entity.HasOne(d => d.VinInContainer).WithOne(p => p.TbdPlannedSequence)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tbd_Planned_Sequence_tbd_VINs_In_Container");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TbdPlannedSequence> entity);
    }
}
