// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using production_supply_system.EntityFramework.DAL.TestContext;
using production_supply_system.EntityFramework.DAL.TestContext.CustomsSchema;
using production_supply_system.EntityFramework.DAL.TestContext.dboSchema;
using production_supply_system.EntityFramework.DAL.TestContext.DocmapperSchema;
using production_supply_system.EntityFramework.DAL.TestContext.InboundSchema;
using production_supply_system.EntityFramework.DAL.TestContext.MasterSchema;
using production_supply_system.EntityFramework.DAL.TestContext.PartscontrolSchema;
using production_supply_system.EntityFramework.DAL.TestContext.PlanningSchema;
using production_supply_system.EntityFramework.DAL.TestContext.UsersSchema;
using System;
using System.Collections.Generic;

#nullable disable

namespace production_supply_system.EntityFramework.DAL.TestContext.Configurations
{
    public partial class TbdTracingConfiguration : IEntityTypeConfiguration<TbdTracing>
    {
        public void Configure(EntityTypeBuilder<TbdTracing> entity)
        {
            entity.HasOne(d => d.Carrier).WithMany(p => p.TbdTracings).HasConstraintName("FK_tbd_Tracing_tbd_Carriers");

            entity.HasOne(d => d.ContainerInLot).WithMany(p => p.TbdTracings)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tbd_Tracing_tbd_Containers_In_Lot");

            entity.HasOne(d => d.TraceLocation).WithMany(p => p.TbdTracings)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tbd_Tracing_tbd_Locations1");

            entity.HasOne(d => d.TraceTransport).WithMany(p => p.TbdTracings).HasConstraintName("FK_tbd_Tracing_tbd_Transports");

            entity.HasOne(d => d.TransportationType).WithMany(p => p.TbdTracings).HasConstraintName("FK_tbd_Tracing_tbd_Types_Of_Transportation");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TbdTracing> entity);
    }
}
