// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using production_supply_system.EntityFramework.DAL.TestContext.CustomsSchema;
using production_supply_system.EntityFramework.DAL.TestContext.dboSchema;
using production_supply_system.EntityFramework.DAL.TestContext.DocmapperSchema;
using production_supply_system.EntityFramework.DAL.TestContext.InboundSchema;
using production_supply_system.EntityFramework.DAL.TestContext.MasterSchema;
using production_supply_system.EntityFramework.DAL.TestContext.PartscontrolSchema;
using production_supply_system.EntityFramework.DAL.TestContext.PlanningSchema;
using production_supply_system.EntityFramework.DAL.TestContext.UsersSchema;


namespace production_supply_system.EntityFramework.DAL.TestContext.MasterSchema;

[Table("tbd_Processes_Steps", Schema = "Master")]
public partial class TbdProcessesStep
{
    [Key]
    [Column("Process_Step_Id")]
    public int ProcessStepId { get; set; }

    [Column("Process_Id")]
    public int ProcessId { get; set; }

    public int Step { get; set; }

    [Column("Docmapper_Id")]
    public int DocmapperId { get; set; }

    [Column("Section_Id")]
    public int SectionId { get; set; }

    [Column("Step_Name")]
    [StringLength(50)]
    public string StepName { get; set; } = null!;

    [ForeignKey("DocmapperId")]
    [InverseProperty("TbdProcessesSteps")]
    public virtual TbdDocmapper Docmapper { get; set; } = null!;

    [ForeignKey("ProcessId")]
    [InverseProperty("TbdProcessesSteps")]
    public virtual TbdProcess Process { get; set; } = null!;

    [ForeignKey("SectionId")]
    [InverseProperty("TbdProcessesSteps")]
    public virtual TbdSection Section { get; set; } = null!;
}