// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

using production_supply_system.EntityFramework.DAL.Models.MasterSchema;

#nullable disable

namespace production_supply_system.EntityFramework.DAL.Models.Configurations
{
    public partial class ProcessesStepConfiguration : IEntityTypeConfiguration<ProcessesStep>
    {
        public void Configure(EntityTypeBuilder<ProcessesStep> entity)
        {
            entity.HasKey(e => e.ProcessStepId).HasName("PK_Processes_Steps");

            //entity.HasOne(d => d.Docmapper).WithMany(p => p.ProcessesSteps)
            //    .OnDelete(DeleteBehavior.ClientSetNull)
            //    .HasConstraintName("FK_Processes_Steps_tbd_Docmapper");

            entity.HasOne(d => d.Process).WithMany(p => p.ProcessesSteps)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Processes_Steps_Processes");

            entity.HasOne(d => d.Section).WithMany(p => p.ProcessesSteps)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Processes_Steps_Sections");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ProcessesStep> entity);
    }
}
