// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using production_supply_system.EntityFramework.DAL.Models;
using production_supply_system.EntityFramework.DAL.Models.CustomsSchema;
using production_supply_system.EntityFramework.DAL.Models.dboSchema;
using production_supply_system.EntityFramework.DAL.Models.DocmapperSchema;
using production_supply_system.EntityFramework.DAL.Models.InboundSchema;
using production_supply_system.EntityFramework.DAL.Models.MasterSchema;
using production_supply_system.EntityFramework.DAL.Models.PartscontrolSchema;
using production_supply_system.EntityFramework.DAL.Models.PlanningSchema;
using production_supply_system.EntityFramework.DAL.Models.UsersSchema;
using System;
using System.Collections.Generic;

#nullable disable

namespace production_supply_system.EntityFramework.DAL.Models.Configurations
{
    public partial class CustomsPartConfiguration : IEntityTypeConfiguration<CustomsPart>
    {
        public void Configure(EntityTypeBuilder<CustomsPart> entity)
        {
            entity.HasKey(e => e.PartNumberId).HasName("PK_tbd_CustomsParts");

            entity.Property(e => e.PartNumberId).ValueGeneratedNever();
            entity.Property(e => e.DateAdd).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.PartType).WithMany(p => p.CustomsParts)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tbd_CustomsParts_tbd_PartTypes");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CustomsPart> entity);
    }
}
