// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using production_supply_system.EntityFramework.DAL.Models;
using production_supply_system.EntityFramework.DAL.Models.CustomsSchema;
using production_supply_system.EntityFramework.DAL.Models.dboSchema;
using production_supply_system.EntityFramework.DAL.Models.DocmapperSchema;
using production_supply_system.EntityFramework.DAL.Models.InboundSchema;
using production_supply_system.EntityFramework.DAL.Models.MasterSchema;
using production_supply_system.EntityFramework.DAL.Models.PartscontrolSchema;
using production_supply_system.EntityFramework.DAL.Models.PlanningSchema;
using production_supply_system.EntityFramework.DAL.Models.UsersSchema;
using System;
using System.Collections.Generic;

#nullable disable

namespace production_supply_system.EntityFramework.DAL.Models.Configurations
{
    public partial class PartsInContainerConfiguration : IEntityTypeConfiguration<PartsInContainer>
    {
        public void Configure(EntityTypeBuilder<PartsInContainer> entity)
        {
            entity.HasKey(e => e.PartInContainerId).HasName("PK_tbd_PartsInContainer");

            entity.HasOne(d => d.Case).WithMany(p => p.PartsInContainers).HasConstraintName("FK_tbd_Parts_In_Container_tbd_Cases");

            entity.HasOne(d => d.ContainerInLot).WithMany(p => p.PartsInContainers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tbd_PartsInContainer_tbd_ContainersInLot");

            entity.HasOne(d => d.PartInvoice).WithMany(p => p.PartsInContainers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tbd_PartsInContainer_tbd_Invoices");

            entity.HasOne(d => d.PartNumber).WithMany(p => p.PartsInContainers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tbd_PartsInContainer_tbd_CustomsParts");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PartsInContainer> entity);
    }
}
