// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using production_supply_system.EntityFramework.DAL.Models;
using production_supply_system.EntityFramework.DAL.Models.CustomsSchema;
using production_supply_system.EntityFramework.DAL.Models.dboSchema;
using production_supply_system.EntityFramework.DAL.Models.DocmapperSchema;
using production_supply_system.EntityFramework.DAL.Models.InboundSchema;
using production_supply_system.EntityFramework.DAL.Models.MasterSchema;
using production_supply_system.EntityFramework.DAL.Models.PartscontrolSchema;
using production_supply_system.EntityFramework.DAL.Models.PlanningSchema;
using production_supply_system.EntityFramework.DAL.Models.UsersSchema;
using System;
using System.Collections.Generic;

#nullable disable

namespace production_supply_system.EntityFramework.DAL.Models.Configurations
{
    public partial class TracingConfiguration : IEntityTypeConfiguration<Tracing>
    {
        public void Configure(EntityTypeBuilder<Tracing> entity)
        {
            entity.HasOne(d => d.Carrier).WithMany(p => p.Tracings).HasConstraintName("FK_tbd_Tracing_tbd_Carriers");

            entity.HasOne(d => d.ContainerInLot).WithMany(p => p.Tracings)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tbd_Tracing_tbd_Containers_In_Lot");

            entity.HasOne(d => d.TraceLocation).WithMany(p => p.Tracings)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tbd_Tracing_tbd_Locations1");

            entity.HasOne(d => d.TraceTransport).WithMany(p => p.Tracings).HasConstraintName("FK_tbd_Tracing_tbd_Transports");

            entity.HasOne(d => d.TransportationType).WithMany(p => p.Tracings).HasConstraintName("FK_tbd_Tracing_tbd_Types_Of_Transportation");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Tracing> entity);
    }
}
