//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BLL.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на checking {0} from {1} lines.
        /// </summary>
        public static string CheckingProgress {
            get {
                return ResourceManager.GetString("CheckingProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на completed.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на container &apos;{0}&apos; is missing container type information.
        /// </summary>
        public static string ContainerTypeMissing {
            get {
                return ResourceManager.GetString("ContainerTypeMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на container type &apos;{0}&apos; is missing in static data.
        /// </summary>
        public static string ContainerTypeMissingInStaticData {
            get {
                return ResourceManager.GetString("ContainerTypeMissingInStaticData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на error getting type for part.
        /// </summary>
        public static string ErrorGettingTypeForPart {
            get {
                return ResourceManager.GetString("ErrorGettingTypeForPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на error in generating the invoice number for the customs clearance.
        /// </summary>
        public static string ErrorInvoceNumberCustomsClearance {
            get {
                return ResourceManager.GetString("ErrorInvoceNumberCustomsClearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на there are errors that prevent further continuation, correct the errors in the file &apos;{0}&apos;.
        /// </summary>
        public static string ErrorsInFile {
            get {
                return ResourceManager.GetString("ErrorsInFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на dd/MM/yyyy.
        /// </summary>
        public static string ExportFormatDate {
            get {
                return ResourceManager.GetString("ExportFormatDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на the final location was not found when generating tracing.
        /// </summary>
        public static string FinalLocationNotFound {
            get {
                return ResourceManager.GetString("FinalLocationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на document with invoice number &apos;{0}&apos; has already been uploaded.
        /// </summary>
        public static string InvoiceNumberHasBeenUploaded {
            get {
                return ResourceManager.GetString("InvoiceNumberHasBeenUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на getting model variants list.
        /// </summary>
        public static string LogBodyModelVariantGet {
            get {
                return ResourceManager.GetString("LogBodyModelVariantGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на adding new bom part.
        /// </summary>
        public static string LogBomPartAdd {
            get {
                return ResourceManager.GetString("LogBomPartAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на searching for an existing bom part by part number &apos;{0}&apos;.
        /// </summary>
        public static string LogBomPartGetExisting {
            get {
                return ResourceManager.GetString("LogBomPartGetExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на getting list bom parts.
        /// </summary>
        public static string LogBomPartsGet {
            get {
                return ResourceManager.GetString("LogBomPartsGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на getting list carriers.
        /// </summary>
        public static string LogCarrierGet {
            get {
                return ResourceManager.GetString("LogCarrierGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на getting carrier by id &apos;{0}&apos;.
        /// </summary>
        public static string LogCarrierGetById {
            get {
                return ResourceManager.GetString("LogCarrierGetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на adding new case.
        /// </summary>
        public static string LogCaseAdd {
            get {
                return ResourceManager.GetString("LogCaseAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на getting cases list.
        /// </summary>
        public static string LogCaseGet {
            get {
                return ResourceManager.GetString("LogCaseGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на getting case by id &apos;{0}&apos;.
        /// </summary>
        public static string LogCaseGetById {
            get {
                return ResourceManager.GetString("LogCaseGetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на adding new container.
        /// </summary>
        public static string LogContainersInLotAdd {
            get {
                return ResourceManager.GetString("LogContainersInLotAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на getting container &apos;{0}&apos; in open lot.
        /// </summary>
        public static string LogContainersInLotByOpenLot {
            get {
                return ResourceManager.GetString("LogContainersInLotByOpenLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на getting containers list.
        /// </summary>
        public static string LogContainersInLotGet {
            get {
                return ResourceManager.GetString("LogContainersInLotGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на getting container by id &apos;{0}&apos;.
        /// </summary>
        public static string LogContainersInLotGetById {
            get {
                return ResourceManager.GetString("LogContainersInLotGetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на getting containers by lot id &apos;{0}&apos;.
        /// </summary>
        public static string LogContainersInLotGetByLotId {
            get {
                return ResourceManager.GetString("LogContainersInLotGetByLotId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на adding new customs clearance.
        /// </summary>
        public static string LogCustomsClearanceAdd {
            get {
                return ResourceManager.GetString("LogCustomsClearanceAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на getting customs clearance list.
        /// </summary>
        public static string LogCustomsClearanceGet {
            get {
                return ResourceManager.GetString("LogCustomsClearanceGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на adding new customs part.
        /// </summary>
        public static string LogCustomsPartAdd {
            get {
                return ResourceManager.GetString("LogCustomsPartAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на getting customs parts list.
        /// </summary>
        public static string LogCustomsPartGet {
            get {
                return ResourceManager.GetString("LogCustomsPartGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на getting customs part by part number id &apos;{0}&apos;.
        /// </summary>
        public static string LogCustomsPartGetById {
            get {
                return ResourceManager.GetString("LogCustomsPartGetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на adding new docmapper.
        /// </summary>
        public static string LogDocmapperAdd {
            get {
                return ResourceManager.GetString("LogDocmapperAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на adding new docmapper column.
        /// </summary>
        public static string LogDocmapperColumnAdd {
            get {
                return ResourceManager.GetString("LogDocmapperColumnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на getting list docmapper columns.
        /// </summary>
        public static string LogDocmapperColumnGet {
            get {
                return ResourceManager.GetString("LogDocmapperColumnGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на getting docmapper column by id &apos;{0}&apos;.
        /// </summary>
        public static string LogDocmapperColumnGetById {
            get {
                return ResourceManager.GetString("LogDocmapperColumnGetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на refreshing docmapper columns.
        /// </summary>
        public static string LogDocmapperColumnRefresh {
            get {
                return ResourceManager.GetString("LogDocmapperColumnRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на adding new document content.
        /// </summary>
        public static string LogDocmapperContentAdd {
            get {
                return ResourceManager.GetString("LogDocmapperContentAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на deleting docmapper content by id &apos;{0}&apos;.
        /// </summary>
        public static string LogDocmapperContentDeleteById {
            get {
                return ResourceManager.GetString("LogDocmapperContentDeleteById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на getting docmapper content by docmapper id &apos;{0}&apos;.
        /// </summary>
        public static string LogDocmapperContentGetByDocmapperId {
            get {
                return ResourceManager.GetString("LogDocmapperContentGetByDocmapperId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на getting missing content.
        /// </summary>
        public static string LogDocmapperContentGetMissing {
            get {
                return ResourceManager.GetString("LogDocmapperContentGetMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на refreshing docmapper content.
        /// </summary>
        public static string LogDocmapperContentRefresh {
            get {
                return ResourceManager.GetString("LogDocmapperContentRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на updating document content.
        /// </summary>
        public static string LogDocmapperContentUpdate {
            get {
                return ResourceManager.GetString("LogDocmapperContentUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на getting list docmappers.
        /// </summary>
        public static string LogDocmapperGet {
            get {
                return ResourceManager.GetString("LogDocmapperGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на getting docmapper by id &apos;{0}&apos;.
        /// </summary>
        public static string LogDocmapperGetById {
            get {
                return ResourceManager.GetString("LogDocmapperGetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на refreshing docmappers.
        /// </summary>
        public static string LogDocmapperRefresh {
            get {
                return ResourceManager.GetString("LogDocmapperRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на updating docmapper.
        /// </summary>
        public static string LogDocmapperUpdate {
            get {
                return ResourceManager.GetString("LogDocmapperUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на adding comment &apos;{0}&apos; to row &apos;{1}&apos; and column &apos;{2}&apos;.
        /// </summary>
        public static string LogExcelAddCommentAndFillRowAndColumn {
            get {
                return ResourceManager.GetString("LogExcelAddCommentAndFillRowAndColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на filling cells in the document &apos;{0}&apos; on sheet name &apos;{1}&apos;.
        /// </summary>
        public static string LogExcelFillCellsInDocument {
            get {
                return ResourceManager.GetString("LogExcelFillCellsInDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на filling row &apos;{0}&apos; and column &apos;{1}&apos;.
        /// </summary>
        public static string LogExcelFillRowAndColumn {
            get {
                return ResourceManager.GetString("LogExcelFillRowAndColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на header validation on a line №&apos;{0}&apos;.
        /// </summary>
        public static string LogExcelHeaderValidation {
            get {
                return ResourceManager.GetString("LogExcelHeaderValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на parsing a file &apos;{0}&apos; from a sheet &apos;{1}.
        /// </summary>
        public static string LogExcelParsingFileFromSheet {
            get {
                return ResourceManager.GetString("LogExcelParsingFileFromSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на sheet &apos;{0}&apos; was not found.
        /// </summary>
        public static string LogExcelSheetNotFound {
            get {
                return ResourceManager.GetString("LogExcelSheetNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на searching sheet &apos;{0}&apos; in the document.
        /// </summary>
        public static string LogExcelSheetSearch {
            get {
                return ResourceManager.GetString("LogExcelSheetSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на in place of the expected &apos;{0}&apos; is located &apos;{1}.
        /// </summary>
        public static string LogExceptionExpectedPlace {
            get {
                return ResourceManager.GetString("LogExceptionExpectedPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на starting export a file {0}.
        /// </summary>
        public static string LogExportFile {
            get {
                return ResourceManager.GetString("LogExportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на adding new invoice.
        /// </summary>
        public static string LogInvoiceAdd {
            get {
                return ResourceManager.GetString("LogInvoiceAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на getting invoices list.
        /// </summary>
        public static string LogInvoiceGet {
            get {
                return ResourceManager.GetString("LogInvoiceGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на getting invoice by id &apos;{0}.
        /// </summary>
        public static string LogInvoiceGetById {
            get {
                return ResourceManager.GetString("LogInvoiceGetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на filter locations by location type &apos;{0}&apos;.
        /// </summary>
        public static string LogLocationFilterByType {
            get {
                return ResourceManager.GetString("LogLocationFilterByType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на getting final location.
        /// </summary>
        public static string LogLocationFinalGet {
            get {
                return ResourceManager.GetString("LogLocationFinalGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на getting locations list.
        /// </summary>
        public static string LogLocationGet {
            get {
                return ResourceManager.GetString("LogLocationGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на getting location by id &apos;{0}&apos;.
        /// </summary>
        public static string LogLocationGetById {
            get {
                return ResourceManager.GetString("LogLocationGetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на adding new lot.
        /// </summary>
        public static string LogLotAdd {
            get {
                return ResourceManager.GetString("LogLotAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на getting lots list.
        /// </summary>
        public static string LogLotGet {
            get {
                return ResourceManager.GetString("LogLotGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на getting lot by id &apos;{0}&apos;.
        /// </summary>
        public static string LogLotGetById {
            get {
                return ResourceManager.GetString("LogLotGetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на adding new part in container.
        /// </summary>
        public static string LogPartsInContainerAdd {
            get {
                return ResourceManager.GetString("LogPartsInContainerAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на getting parts in container list.
        /// </summary>
        public static string LogPartsInContainerGet {
            get {
                return ResourceManager.GetString("LogPartsInContainerGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на getting parts by container id &apos;{0}&apos;.
        /// </summary>
        public static string LogPartsInContainerGetByContainerId {
            get {
                return ResourceManager.GetString("LogPartsInContainerGetByContainerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на adding new part in invoice.
        /// </summary>
        public static string LogPartsInInvoiceAdd {
            get {
                return ResourceManager.GetString("LogPartsInInvoiceAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на getting parts in invoice list.
        /// </summary>
        public static string LogPartsInInvoiceGet {
            get {
                return ResourceManager.GetString("LogPartsInInvoiceGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на getting process by id &apos;{0}&apos;.
        /// </summary>
        public static string LogProcessGetById {
            get {
                return ResourceManager.GetString("LogProcessGetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на getting process steps for app process {0}.
        /// </summary>
        public static string LogProcessStepGet {
            get {
                return ResourceManager.GetString("LogProcessStepGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на getting process steps by section id &apos;{0}&apos;.
        /// </summary>
        public static string LogProcessStepGetBySectionId {
            get {
                return ResourceManager.GetString("LogProcessStepGetBySectionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на getting purchase orders list.
        /// </summary>
        public static string LogPurchaseOrderGet {
            get {
                return ResourceManager.GetString("LogPurchaseOrderGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на getting purchase order by id &apos;{0}&apos;.
        /// </summary>
        public static string LogPurchaseOrderGetById {
            get {
                return ResourceManager.GetString("LogPurchaseOrderGetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на getting section by id &apos;{0}&apos;.
        /// </summary>
        public static string LogSectionGetById {
            get {
                return ResourceManager.GetString("LogSectionGetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на getting list shippers.
        /// </summary>
        public static string LogShipperGet {
            get {
                return ResourceManager.GetString("LogShipperGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на getting shipper by id &apos;{0}&apos;.
        /// </summary>
        public static string LogShipperGetById {
            get {
                return ResourceManager.GetString("LogShipperGetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на getting delivery terms list.
        /// </summary>
        public static string LogTermsOfDeliveryGet {
            get {
                return ResourceManager.GetString("LogTermsOfDeliveryGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на getting delivery term by id &apos;{0}&apos;.
        /// </summary>
        public static string LogTermsOfDeliveryGetById {
            get {
                return ResourceManager.GetString("LogTermsOfDeliveryGetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на adding new tracing.
        /// </summary>
        public static string LogTracingAdd {
            get {
                return ResourceManager.GetString("LogTracingAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на getting tracing list.
        /// </summary>
        public static string LogTracingGet {
            get {
                return ResourceManager.GetString("LogTracingGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на adding new transport.
        /// </summary>
        public static string LogTransportAdd {
            get {
                return ResourceManager.GetString("LogTransportAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на getting transport list.
        /// </summary>
        public static string LogTransportGet {
            get {
                return ResourceManager.GetString("LogTransportGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на getting transport by id &apos;{0}&apos;.
        /// </summary>
        public static string LogTransportGetById {
            get {
                return ResourceManager.GetString("LogTransportGetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на refreshing transport.
        /// </summary>
        public static string LogTransportRefresh {
            get {
                return ResourceManager.GetString("LogTransportRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на getting container types list.
        /// </summary>
        public static string LogTypesOfContainerGet {
            get {
                return ResourceManager.GetString("LogTypesOfContainerGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на getting container type by id &apos;{0}&apos;.
        /// </summary>
        public static string LogTypesOfContainerGetById {
            get {
                return ResourceManager.GetString("LogTypesOfContainerGetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на getting container type by container type name &apos;{0}&apos;.
        /// </summary>
        public static string LogTypesOfContainerGetByTypeName {
            get {
                return ResourceManager.GetString("LogTypesOfContainerGetByTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на getting a location type by id &apos;{0}.
        /// </summary>
        public static string LogTypesOfLocationGetById {
            get {
                return ResourceManager.GetString("LogTypesOfLocationGetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на getting order type by id &apos;{0}&apos;.
        /// </summary>
        public static string LogTypesOfOrderGetById {
            get {
                return ResourceManager.GetString("LogTypesOfOrderGetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на getting list packing types.
        /// </summary>
        public static string LogTypesOfPackingGet {
            get {
                return ResourceManager.GetString("LogTypesOfPackingGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на getting a package type by id &apos;{0}.
        /// </summary>
        public static string LogTypesOfPackingGetById {
            get {
                return ResourceManager.GetString("LogTypesOfPackingGetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на getting a package type by type name &apos;{0}.
        /// </summary>
        public static string LogTypesOfPackingGetByTypeName {
            get {
                return ResourceManager.GetString("LogTypesOfPackingGetByTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на getting list part types.
        /// </summary>
        public static string LogTypesOfPartGet {
            get {
                return ResourceManager.GetString("LogTypesOfPartGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на getting part type by id &apos;{0}&apos;.
        /// </summary>
        public static string LogTypesOfPartGetById {
            get {
                return ResourceManager.GetString("LogTypesOfPartGetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на getting part type by part type name &apos;{0}&apos;.
        /// </summary>
        public static string LogTypesOfPartGetByPartTypeName {
            get {
                return ResourceManager.GetString("LogTypesOfPartGetByPartTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на getting transport types list.
        /// </summary>
        public static string LogTypesOfTransportGet {
            get {
                return ResourceManager.GetString("LogTypesOfTransportGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на getting transport type by id &apos;{0}&apos;.
        /// </summary>
        public static string LogTypesOfTransportGetById {
            get {
                return ResourceManager.GetString("LogTypesOfTransportGetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на getting users list.
        /// </summary>
        public static string LogUsersGet {
            get {
                return ResourceManager.GetString("LogUsersGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на getting user by account &apos;{0}&apos; from received list.
        /// </summary>
        public static string LogUsersGetByAccount {
            get {
                return ResourceManager.GetString("LogUsersGetByAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на user not found.
        /// </summary>
        public static string LogUsersNotFound {
            get {
                return ResourceManager.GetString("LogUsersNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на user with account &apos;{0}&apos; not found.
        /// </summary>
        public static string LogUsersNotFoundWithAccount {
            get {
                return ResourceManager.GetString("LogUsersNotFoundWithAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на adding new vin container.
        /// </summary>
        public static string LogVinsInContainerAdd {
            get {
                return ResourceManager.GetString("LogVinsInContainerAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на getting vin containers list.
        /// </summary>
        public static string LogVinsInContainerGet {
            get {
                return ResourceManager.GetString("LogVinsInContainerGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на with result: &apos;{0}&apos;.
        /// </summary>
        public static string LogWithResult {
            get {
                return ResourceManager.GetString("LogWithResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на -.
        /// </summary>
        public static string LotNumberEmptySymbol {
            get {
                return ResourceManager.GetString("LotNumberEmptySymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на not valid VIN &apos;{0}&apos;.
        /// </summary>
        public static string NotValidVIN {
            get {
                return ResourceManager.GetString("NotValidVIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на packing type &apos;{0}&apos; is missing in static data.
        /// </summary>
        public static string PackingTypeMissingInStaticData {
            get {
                return ResourceManager.GetString("PackingTypeMissingInStaticData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на part by number &apos;{0}&apos; not found.
        /// </summary>
        public static string PartByNumberNotFound {
            get {
                return ResourceManager.GetString("PartByNumberNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на start of get data to partner 2 to export file.
        /// </summary>
        public static string Partner2GetAllTracing {
            get {
                return ResourceManager.GetString("Partner2GetAllTracing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на part number &apos;{0}&apos; has different prices.
        /// </summary>
        public static string PartNumberDifferentPrice {
            get {
                return ResourceManager.GetString("PartNumberDifferentPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please wait.
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на price by part number &apos;{0}&apos; not found.
        /// </summary>
        public static string PriceByPartNumberNotFound {
            get {
                return ResourceManager.GetString("PriceByPartNumberNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на quantity by part number &apos;{0}&apos; not found.
        /// </summary>
        public static string QuantityByPartNumberNotFound {
            get {
                return ResourceManager.GetString("QuantityByPartNumberNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Release not found for body &apos;{0}&apos; and part &apos;{1}&apos;, check the correctness of the input or contact the DSS.
        /// </summary>
        public static string ReleaseNotFound {
            get {
                return ResourceManager.GetString("ReleaseNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на saving a case to the {0} from {1}.
        /// </summary>
        public static string SavingProgressCase {
            get {
                return ResourceManager.GetString("SavingProgressCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на saving a container to the {0} from {1}.
        /// </summary>
        public static string SavingProgressContainer {
            get {
                return ResourceManager.GetString("SavingProgressContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на saving a customs clearance to the {0} from {1}.
        /// </summary>
        public static string SavingProgressCustomsClearance {
            get {
                return ResourceManager.GetString("SavingProgressCustomsClearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на saving a customs part to the {0} from {1}.
        /// </summary>
        public static string SavingProgressCustomsPart {
            get {
                return ResourceManager.GetString("SavingProgressCustomsPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на saving a detail to the container {0} from {1}.
        /// </summary>
        public static string SavingProgressDetailInContainer {
            get {
                return ResourceManager.GetString("SavingProgressDetailInContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на saving a part in invoice to the {0} from {1}.
        /// </summary>
        public static string SavingProgressPartInInvoice {
            get {
                return ResourceManager.GetString("SavingProgressPartInInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на saving a tracing to the {0} from {1}.
        /// </summary>
        public static string SavingProgressTracing {
            get {
                return ResourceManager.GetString("SavingProgressTracing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на saving a vin container to the {0} from {1}.
        /// </summary>
        public static string SavingProgressVinContainer {
            get {
                return ResourceManager.GetString("SavingProgressVinContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A.
        /// </summary>
        public static string SymbolBody {
            get {
                return ResourceManager.GetString("SymbolBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на B.
        /// </summary>
        public static string SymbolParts {
            get {
                return ResourceManager.GetString("SymbolParts", resourceCulture);
            }
        }
    }
}
