// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using production_supply_system.EntityFramework.DAL.Models.CustomsSchema;
using production_supply_system.EntityFramework.DAL.Models.dboSchema;
using production_supply_system.EntityFramework.DAL.Models.DocmapperSchema;
using production_supply_system.EntityFramework.DAL.Models.InboundSchema;
using production_supply_system.EntityFramework.DAL.Models.MasterSchema;
using production_supply_system.EntityFramework.DAL.Models.PartscontrolSchema;
using production_supply_system.EntityFramework.DAL.Models.PlanningSchema;
using production_supply_system.EntityFramework.DAL.Models.UsersSchema;


namespace production_supply_system.EntityFramework.DAL.Models.PartscontrolSchema;

[Table("tbd_Purchase_Orders", Schema = "Partscontrol")]
[Index("PurchaseOrderNumber", Name = "IX_tbd_PurchaseOrders", IsUnique = true)]
public partial class PurchaseOrder
{
    [Key]
    [Column("Purchase_Order_Id")]
    public int PurchaseOrderId { get; set; }

    [Column("Shipper_Id")]
    public int ShipperId { get; set; }

    [Column("Order_Type_Id")]
    public int OrderTypeId { get; set; }

    [Column("Purchase_Order_Number")]
    [StringLength(10)]
    public string PurchaseOrderNumber { get; set; } = null!;

    [Column("Purchase_Order_Date")]
    public DateOnly PurchaseOrderDate { get; set; }

    [ForeignKey("OrderTypeId")]
    [InverseProperty("PurchaseOrders")]
    public virtual TypesOfOrder OrderType { get; set; } = null!;

    [ForeignKey("ShipperId")]
    [InverseProperty("PurchaseOrders")]
    public virtual Shipper Shipper { get; set; } = null!;

    [InverseProperty("PurchaseOrder")]
    public virtual ICollection<Invoice> Invoices { get; set; } = new List<Invoice>();

    [InverseProperty("LotPurchaseOrder")]
    public virtual ICollection<Lot> Lots { get; set; } = new List<Lot>();
}