// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using production_supply_system.EntityFramework.DAL.TestContext.CustomsSchema;
using production_supply_system.EntityFramework.DAL.TestContext.dboSchema;
using production_supply_system.EntityFramework.DAL.TestContext.DocmapperSchema;
using production_supply_system.EntityFramework.DAL.TestContext.InboundSchema;
using production_supply_system.EntityFramework.DAL.TestContext.MasterSchema;
using production_supply_system.EntityFramework.DAL.TestContext.PartscontrolSchema;
using production_supply_system.EntityFramework.DAL.TestContext.PlanningSchema;
using production_supply_system.EntityFramework.DAL.TestContext.UsersSchema;


namespace production_supply_system.EntityFramework.DAL.TestContext.PlanningSchema;

[Table("tbd_Planned_Sequence", Schema = "Planning")]
[Index("VinInContainerId", Name = "IX_tbd_Planned_Sequence_VIN_In_Cont", IsUnique = true)]
public partial class TbdPlannedSequence
{
    [Key]
    [Column("Planned_Sequence_Id")]
    public int PlannedSequenceId { get; set; }

    [Column("VIN_In_Container_Id")]
    public int VinInContainerId { get; set; }

    [Column("PP_Order")]
    public int? PpOrder { get; set; }

    [Column("CCR_Order")]
    public int? CcrOrder { get; set; }

    [Column("Status_For_SFS_Upload_Id")]
    public int? StatusForSfsUploadId { get; set; }

    [Column("Is_Suspicious")]
    public int? IsSuspicious { get; set; }

    [Column("Is_Unyelding")]
    public int? IsUnyelding { get; set; }

    [ForeignKey("StatusForSfsUploadId")]
    [InverseProperty("TbdPlannedSequences")]
    public virtual TbdStatusesForSfsUpload? StatusForSfsUpload { get; set; }

    [ForeignKey("VinInContainerId")]
    [InverseProperty("TbdPlannedSequence")]
    public virtual TbdVinsInContainer VinInContainer { get; set; } = null!;
}