// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using production_supply_system.EntityFramework.DAL.TestContext.CustomsSchema;
using production_supply_system.EntityFramework.DAL.TestContext.dboSchema;
using production_supply_system.EntityFramework.DAL.TestContext.DocmapperSchema;
using production_supply_system.EntityFramework.DAL.TestContext.InboundSchema;
using production_supply_system.EntityFramework.DAL.TestContext.MasterSchema;
using production_supply_system.EntityFramework.DAL.TestContext.PartscontrolSchema;
using production_supply_system.EntityFramework.DAL.TestContext.PlanningSchema;
using production_supply_system.EntityFramework.DAL.TestContext.UsersSchema;


namespace production_supply_system.EntityFramework.DAL.TestContext.UsersSchema;

[Table("tbd_Users", Schema = "Users")]
[Index("Account", Name = "UQ_tbd_Users_Account", IsUnique = true)]
public partial class TbdUser
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [StringLength(10)]
    public string Account { get; set; } = null!;

    [StringLength(30)]
    public string Name { get; set; } = null!;

    [StringLength(30)]
    public string Surname { get; set; } = null!;

    [StringLength(30)]
    public string Patronymic { get; set; } = null!;

    [Column("Section_Id")]
    public int SectionId { get; set; }

    [ForeignKey("SectionId")]
    [InverseProperty("TbdUsers")]
    public virtual TbdSection Section { get; set; } = null!;
}