// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using production_supply_system.EntityFramework.DAL.TestContext.CustomsSchema;
using production_supply_system.EntityFramework.DAL.TestContext.dboSchema;
using production_supply_system.EntityFramework.DAL.TestContext.DocmapperSchema;
using production_supply_system.EntityFramework.DAL.TestContext.InboundSchema;
using production_supply_system.EntityFramework.DAL.TestContext.MasterSchema;
using production_supply_system.EntityFramework.DAL.TestContext.PartscontrolSchema;
using production_supply_system.EntityFramework.DAL.TestContext.PlanningSchema;
using production_supply_system.EntityFramework.DAL.TestContext.UsersSchema;


namespace production_supply_system.EntityFramework.DAL.TestContext.InboundSchema;

[Table("tbd_Containers_In_Lot", Schema = "Inbound")]
public partial class TbdContainersInLot
{
    [Key]
    [Column("Container_In_Lot_Id")]
    public int ContainerInLotId { get; set; }

    [Column("Lot_Id")]
    public int LotId { get; set; }

    [Column("Container_Number")]
    [StringLength(11)]
    public string ContainerNumber { get; set; } = null!;

    [Column("Seal_Number")]
    [StringLength(20)]
    public string? SealNumber { get; set; }

    [Column("Container_Type_Id")]
    public int ContainerTypeId { get; set; }

    [Column("IMO_Cargo")]
    public bool? ImoCargo { get; set; }

    [Column("Storage_Last_Free_Day")]
    public DateOnly? StorageLastFreeDay { get; set; }

    [Column("Detention_Last_Free_Day")]
    public DateOnly? DetentionLastFreeDay { get; set; }

    [Column("Container_Comment")]
    [StringLength(250)]
    public string? ContainerComment { get; set; }

    [Column("Last_Tracing_Update")]
    public DateOnly? LastTracingUpdate { get; set; }

    [Column("CI_OnTheWay")]
    public bool CiOnTheWay { get; set; }

    [ForeignKey("ContainerTypeId")]
    [InverseProperty("TbdContainersInLots")]
    public virtual TbdTypesOfContainer ContainerType { get; set; } = null!;

    [ForeignKey("LotId")]
    [InverseProperty("TbdContainersInLots")]
    public virtual TbdLot Lot { get; set; } = null!;

    [InverseProperty("ContainerInLot")]
    public virtual ICollection<TbdCustomsClearance> TbdCustomsClearances { get; set; } = new List<TbdCustomsClearance>();

    [InverseProperty("ContainerInLot")]
    public virtual ICollection<TbdPartsInContainer> TbdPartsInContainers { get; set; } = new List<TbdPartsInContainer>();

    [InverseProperty("ContainerInLot")]
    public virtual ICollection<TbdTracing> TbdTracings { get; set; } = new List<TbdTracing>();

    [InverseProperty("ContainerInLot")]
    public virtual ICollection<TbdVinsInContainer> TbdVinsInContainers { get; set; } = new List<TbdVinsInContainer>();
}