// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using production_supply_system.EntityFramework.DAL.TestContext.CustomsSchema;
using production_supply_system.EntityFramework.DAL.TestContext.dboSchema;
using production_supply_system.EntityFramework.DAL.TestContext.DocmapperSchema;
using production_supply_system.EntityFramework.DAL.TestContext.InboundSchema;
using production_supply_system.EntityFramework.DAL.TestContext.MasterSchema;
using production_supply_system.EntityFramework.DAL.TestContext.PartscontrolSchema;
using production_supply_system.EntityFramework.DAL.TestContext.PlanningSchema;
using production_supply_system.EntityFramework.DAL.TestContext.UsersSchema;


namespace production_supply_system.EntityFramework.DAL.TestContext.InboundSchema;

[Table("tbd_Cases", Schema = "Inbound")]
public partial class TbdCase
{
    [Key]
    [Column("Case_Id")]
    public int CaseId { get; set; }

    [Column("Case_No")]
    [StringLength(10)]
    public string CaseNo { get; set; } = null!;

    [Column("Net_Weight", TypeName = "decimal(6, 3)")]
    public decimal NetWeight { get; set; }

    [Column("Gross_Weight", TypeName = "decimal(6, 3)")]
    public decimal GrossWeight { get; set; }

    [Column("Packing_Type_Id")]
    public int? PackingTypeId { get; set; }

    [Column(TypeName = "decimal(6, 2)")]
    public decimal? Length { get; set; }

    [Column(TypeName = "decimal(6, 2)")]
    public decimal? Width { get; set; }

    [Column(TypeName = "decimal(6, 2)")]
    public decimal? Height { get; set; }

    [Column(TypeName = "decimal(6, 2)")]
    public decimal? Volume { get; set; }

    [ForeignKey("PackingTypeId")]
    [InverseProperty("TbdCases")]
    public virtual TbdTypesOfPacking? PackingType { get; set; }

    [InverseProperty("Case")]
    public virtual ICollection<TbdPartsInContainer> TbdPartsInContainers { get; set; } = new List<TbdPartsInContainer>();
}