// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using production_supply_system.EntityFramework.DAL.TestContext.CustomsSchema;
using production_supply_system.EntityFramework.DAL.TestContext.dboSchema;
using production_supply_system.EntityFramework.DAL.TestContext.DocmapperSchema;
using production_supply_system.EntityFramework.DAL.TestContext.InboundSchema;
using production_supply_system.EntityFramework.DAL.TestContext.MasterSchema;
using production_supply_system.EntityFramework.DAL.TestContext.PartscontrolSchema;
using production_supply_system.EntityFramework.DAL.TestContext.PlanningSchema;
using production_supply_system.EntityFramework.DAL.TestContext.UsersSchema;


namespace production_supply_system.EntityFramework.DAL.TestContext.InboundSchema;

[Table("tbd_Invoices", Schema = "Inbound")]
[Index("InvoiceNumber", Name = "IX_tbd_Invoices", IsUnique = true)]
public partial class TbdInvoice
{
    [Key]
    [Column("Invoice_Id")]
    public int InvoiceId { get; set; }

    [Column("Invoice_Number")]
    [StringLength(20)]
    public string InvoiceNumber { get; set; } = null!;

    [Column("Invoice_Date")]
    public DateOnly InvoiceDate { get; set; }

    [Column("Shipper_Id")]
    public int ShipperId { get; set; }

    [Column("Purchase_Order_Id")]
    public int? PurchaseOrderId { get; set; }

    [ForeignKey("PurchaseOrderId")]
    [InverseProperty("TbdInvoices")]
    public virtual TbdPurchaseOrder? PurchaseOrder { get; set; }

    [InverseProperty("LotInvoice")]
    public virtual ICollection<TbdLot> TbdLots { get; set; } = new List<TbdLot>();

    [InverseProperty("PartInvoice")]
    public virtual ICollection<TbdPartsInContainer> TbdPartsInContainers { get; set; } = new List<TbdPartsInContainer>();

    [InverseProperty("Invoice")]
    public virtual ICollection<TbdPartsInInvoice> TbdPartsInInvoices { get; set; } = new List<TbdPartsInInvoice>();
}