// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using production_supply_system.EntityFramework.DAL.TestContext.CustomsSchema;
using production_supply_system.EntityFramework.DAL.TestContext.dboSchema;
using production_supply_system.EntityFramework.DAL.TestContext.DocmapperSchema;
using production_supply_system.EntityFramework.DAL.TestContext.InboundSchema;
using production_supply_system.EntityFramework.DAL.TestContext.MasterSchema;
using production_supply_system.EntityFramework.DAL.TestContext.PartscontrolSchema;
using production_supply_system.EntityFramework.DAL.TestContext.PlanningSchema;
using production_supply_system.EntityFramework.DAL.TestContext.UsersSchema;


namespace production_supply_system.EntityFramework.DAL.TestContext.InboundSchema;

[Table("tbd_Locations", Schema = "Inbound")]
public partial class TbdLocation
{
    [Key]
    [Column("Location_Id")]
    public int LocationId { get; set; }

    [Column("Location_Type_Id")]
    public int LocationTypeId { get; set; }

    [Column("Location_Name")]
    [StringLength(50)]
    public string LocationName { get; set; } = null!;

    [StringLength(50)]
    public string? City { get; set; }

    [ForeignKey("LocationTypeId")]
    [InverseProperty("TbdLocations")]
    public virtual TbdTypesOfLocation LocationType { get; set; } = null!;

    [InverseProperty("LotArrivalLocation")]
    public virtual ICollection<TbdLot> TbdLotLotArrivalLocations { get; set; } = new List<TbdLot>();

    [InverseProperty("LotCustomsLocation")]
    public virtual ICollection<TbdLot> TbdLotLotCustomsLocations { get; set; } = new List<TbdLot>();

    [InverseProperty("LotDepartureLocation")]
    public virtual ICollection<TbdLot> TbdLotLotDepartureLocations { get; set; } = new List<TbdLot>();

    [InverseProperty("ShipperDefaultDeliveryLocation")]
    public virtual ICollection<TbdShipper> TbdShippers { get; set; } = new List<TbdShipper>();

    [InverseProperty("TraceLocation")]
    public virtual ICollection<TbdTracing> TbdTracings { get; set; } = new List<TbdTracing>();
}