// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using production_supply_system.EntityFramework.DAL.TestContext.CustomsSchema;
using production_supply_system.EntityFramework.DAL.TestContext.dboSchema;
using production_supply_system.EntityFramework.DAL.TestContext.DocmapperSchema;
using production_supply_system.EntityFramework.DAL.TestContext.InboundSchema;
using production_supply_system.EntityFramework.DAL.TestContext.MasterSchema;
using production_supply_system.EntityFramework.DAL.TestContext.PartscontrolSchema;
using production_supply_system.EntityFramework.DAL.TestContext.PlanningSchema;
using production_supply_system.EntityFramework.DAL.TestContext.UsersSchema;


namespace production_supply_system.EntityFramework.DAL.TestContext.InboundSchema;

[Table("tbd_Parts_In_Container", Schema = "Inbound")]
public partial class TbdPartsInContainer
{
    [Key]
    [Column("Part_In_Container_Id")]
    public int PartInContainerId { get; set; }

    [Column("Container_In_Lot_Id")]
    public int ContainerInLotId { get; set; }

    [Column("Case_Id")]
    public int? CaseId { get; set; }

    [Column("Part_Number_Id")]
    public int PartNumberId { get; set; }

    public int Quantity { get; set; }

    [Column("Part_Invoice_Id")]
    public int PartInvoiceId { get; set; }

    [ForeignKey("CaseId")]
    [InverseProperty("TbdPartsInContainers")]
    public virtual TbdCase? Case { get; set; }

    [ForeignKey("ContainerInLotId")]
    [InverseProperty("TbdPartsInContainers")]
    public virtual TbdContainersInLot ContainerInLot { get; set; } = null!;

    [ForeignKey("PartInvoiceId")]
    [InverseProperty("TbdPartsInContainers")]
    public virtual TbdInvoice PartInvoice { get; set; } = null!;

    [ForeignKey("PartNumberId")]
    [InverseProperty("TbdPartsInContainers")]
    public virtual TbdCustomsPart PartNumber { get; set; } = null!;
}