// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using production_supply_system.EntityFramework.DAL.TestContext.CustomsSchema;
using production_supply_system.EntityFramework.DAL.TestContext.dboSchema;
using production_supply_system.EntityFramework.DAL.TestContext.DocmapperSchema;
using production_supply_system.EntityFramework.DAL.TestContext.InboundSchema;
using production_supply_system.EntityFramework.DAL.TestContext.MasterSchema;
using production_supply_system.EntityFramework.DAL.TestContext.PartscontrolSchema;
using production_supply_system.EntityFramework.DAL.TestContext.PlanningSchema;
using production_supply_system.EntityFramework.DAL.TestContext.UsersSchema;


namespace production_supply_system.EntityFramework.DAL.TestContext.InboundSchema;

[Table("tbd_Parts_In_Invoice", Schema = "Inbound")]
public partial class TbdPartsInInvoice
{
    [Key]
    [Column("Part_In_Invoice_Id")]
    public int PartInInvoiceId { get; set; }

    [Column("Invoice_Id")]
    public int InvoiceId { get; set; }

    [Column("Part_Number_Id")]
    public int PartNumberId { get; set; }

    [Column(TypeName = "decimal(8, 3)")]
    public decimal Quantity { get; set; }

    [Column(TypeName = "decimal(10, 4)")]
    public decimal Price { get; set; }

    [ForeignKey("InvoiceId")]
    [InverseProperty("TbdPartsInInvoices")]
    public virtual TbdInvoice Invoice { get; set; } = null!;

    [ForeignKey("PartNumberId")]
    [InverseProperty("TbdPartsInInvoices")]
    public virtual TbdCustomsPart PartNumber { get; set; } = null!;
}