// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using production_supply_system.EntityFramework.DAL.TestContext.CustomsSchema;
using production_supply_system.EntityFramework.DAL.TestContext.dboSchema;
using production_supply_system.EntityFramework.DAL.TestContext.DocmapperSchema;
using production_supply_system.EntityFramework.DAL.TestContext.InboundSchema;
using production_supply_system.EntityFramework.DAL.TestContext.MasterSchema;
using production_supply_system.EntityFramework.DAL.TestContext.PartscontrolSchema;
using production_supply_system.EntityFramework.DAL.TestContext.PlanningSchema;
using production_supply_system.EntityFramework.DAL.TestContext.UsersSchema;


namespace production_supply_system.EntityFramework.DAL.TestContext.InboundSchema;

[Table("tbd_Shippers", Schema = "Inbound")]
public partial class TbdShipper
{
    [Key]
    [Column("Shipper_Id")]
    public int ShipperId { get; set; }

    [Column("Shipper_Name")]
    [StringLength(20)]
    public string ShipperName { get; set; } = null!;

    [Column("Shipper_Full_Name")]
    [StringLength(100)]
    public string? ShipperFullName { get; set; }

    [Column("Shipper_Default_Delivery_Location_Id")]
    public int? ShipperDefaultDeliveryLocationId { get; set; }

    [ForeignKey("ShipperDefaultDeliveryLocationId")]
    [InverseProperty("TbdShippers")]
    public virtual TbdLocation? ShipperDefaultDeliveryLocation { get; set; }

    [InverseProperty("Shipper")]
    public virtual ICollection<TbdLot> TbdLots { get; set; } = new List<TbdLot>();

    [InverseProperty("Shipper")]
    public virtual ICollection<TbdPurchaseOrder> TbdPurchaseOrders { get; set; } = new List<TbdPurchaseOrder>();
}