// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using production_supply_system.EntityFramework.DAL.TestContext.CustomsSchema;
using production_supply_system.EntityFramework.DAL.TestContext.dboSchema;
using production_supply_system.EntityFramework.DAL.TestContext.DocmapperSchema;
using production_supply_system.EntityFramework.DAL.TestContext.InboundSchema;
using production_supply_system.EntityFramework.DAL.TestContext.MasterSchema;
using production_supply_system.EntityFramework.DAL.TestContext.PartscontrolSchema;
using production_supply_system.EntityFramework.DAL.TestContext.PlanningSchema;
using production_supply_system.EntityFramework.DAL.TestContext.UsersSchema;


namespace production_supply_system.EntityFramework.DAL.TestContext.InboundSchema;

[Table("tbd_Types_Of_Container", Schema = "Inbound")]
public partial class TbdTypesOfContainer
{
    [Key]
    [Column("Container_Type_Id")]
    public int ContainerTypeId { get; set; }

    [Column("Container_Type")]
    [StringLength(10)]
    public string ContainerType { get; set; } = null!;

    [InverseProperty("ContainerType")]
    public virtual ICollection<TbdContainersInLot> TbdContainersInLots { get; set; } = new List<TbdContainersInLot>();
}