// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using production_supply_system.EntityFramework.DAL.TestContext.CustomsSchema;
using production_supply_system.EntityFramework.DAL.TestContext.dboSchema;
using production_supply_system.EntityFramework.DAL.TestContext.DocmapperSchema;
using production_supply_system.EntityFramework.DAL.TestContext.InboundSchema;
using production_supply_system.EntityFramework.DAL.TestContext.MasterSchema;
using production_supply_system.EntityFramework.DAL.TestContext.PartscontrolSchema;
using production_supply_system.EntityFramework.DAL.TestContext.PlanningSchema;
using production_supply_system.EntityFramework.DAL.TestContext.UsersSchema;


namespace production_supply_system.EntityFramework.DAL.TestContext.InboundSchema;

[Table("tbd_Types_Of_Transport", Schema = "Inbound")]
public partial class TbdTypesOfTransport
{
    [Key]
    [Column("Transport_Type_Id")]
    public int TransportTypeId { get; set; }

    [Column("Transport_Type")]
    [StringLength(10)]
    public string TransportType { get; set; } = null!;

    [Column("Transport_Document_Name")]
    [StringLength(10)]
    public string TransportDocumentName { get; set; } = null!;

    [InverseProperty("LotTransportType")]
    public virtual ICollection<TbdLot> TbdLots { get; set; } = new List<TbdLot>();

    [InverseProperty("TransportationType")]
    public virtual ICollection<TbdTracing> TbdTracings { get; set; } = new List<TbdTracing>();
}