// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using production_supply_system.EntityFramework.DAL.TestContext.CustomsSchema;
using production_supply_system.EntityFramework.DAL.TestContext.dboSchema;
using production_supply_system.EntityFramework.DAL.TestContext.DocmapperSchema;
using production_supply_system.EntityFramework.DAL.TestContext.InboundSchema;
using production_supply_system.EntityFramework.DAL.TestContext.MasterSchema;
using production_supply_system.EntityFramework.DAL.TestContext.PartscontrolSchema;
using production_supply_system.EntityFramework.DAL.TestContext.PlanningSchema;
using production_supply_system.EntityFramework.DAL.TestContext.UsersSchema;


namespace production_supply_system.EntityFramework.DAL.TestContext.InboundSchema;

[Table("tbd_Terms_Of_Container_Use", Schema = "Inbound")]
public partial class TbdTermsOfContainerUse
{
    [Key]
    public int Id { get; set; }

    [Column("Init_Date")]
    public DateOnly InitDate { get; set; }

    [Column("Carrier_Id")]
    public int CarrierId { get; set; }

    public int? Detention { get; set; }

    public int? Storage { get; set; }

    [ForeignKey("CarrierId")]
    [InverseProperty("TbdTermsOfContainerUses")]
    public virtual TbdCarrier Carrier { get; set; } = null!;
}