// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using production_supply_system.EntityFramework.DAL.TestContext.CustomsSchema;
using production_supply_system.EntityFramework.DAL.TestContext.dboSchema;
using production_supply_system.EntityFramework.DAL.TestContext.DocmapperSchema;
using production_supply_system.EntityFramework.DAL.TestContext.InboundSchema;
using production_supply_system.EntityFramework.DAL.TestContext.MasterSchema;
using production_supply_system.EntityFramework.DAL.TestContext.PartscontrolSchema;
using production_supply_system.EntityFramework.DAL.TestContext.PlanningSchema;
using production_supply_system.EntityFramework.DAL.TestContext.UsersSchema;


namespace production_supply_system.EntityFramework.DAL.TestContext.InboundSchema;

[Table("tbd_Types_Of_Packing", Schema = "Inbound")]
public partial class TbdTypesOfPacking
{
    [Key]
    [Column("Packing_Type_Id")]
    public int PackingTypeId { get; set; }

    [Column("Supplier_Packing_Type")]
    [StringLength(150)]
    public string SupplierPackingType { get; set; } = null!;

    [Column("Packing_Type")]
    [StringLength(150)]
    public string PackingType { get; set; } = null!;

    [InverseProperty("PackingType")]
    public virtual ICollection<TbdCase> TbdCases { get; set; } = new List<TbdCase>();
}