// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using production_supply_system.EntityFramework.DAL.TestContext.CustomsSchema;
using production_supply_system.EntityFramework.DAL.TestContext.dboSchema;
using production_supply_system.EntityFramework.DAL.TestContext.DocmapperSchema;
using production_supply_system.EntityFramework.DAL.TestContext.InboundSchema;
using production_supply_system.EntityFramework.DAL.TestContext.MasterSchema;
using production_supply_system.EntityFramework.DAL.TestContext.PartscontrolSchema;
using production_supply_system.EntityFramework.DAL.TestContext.PlanningSchema;
using production_supply_system.EntityFramework.DAL.TestContext.UsersSchema;


namespace production_supply_system.EntityFramework.DAL.TestContext.InboundSchema;

[Table("tbd_Terms_Of_Delivery", Schema = "Inbound")]
public partial class TbdTermsOfDelivery
{
    [Key]
    [Column("Delivery_Terms_Id")]
    public int DeliveryTermsId { get; set; }

    [Column("Delivery_Term")]
    [StringLength(5)]
    public string DeliveryTerm { get; set; } = null!;

    [InverseProperty("DeliveryTerms")]
    public virtual ICollection<TbdLot> TbdLots { get; set; } = new List<TbdLot>();
}