// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using production_supply_system.EntityFramework.DAL.TestContext.CustomsSchema;
using production_supply_system.EntityFramework.DAL.TestContext.dboSchema;
using production_supply_system.EntityFramework.DAL.TestContext.DocmapperSchema;
using production_supply_system.EntityFramework.DAL.TestContext.InboundSchema;
using production_supply_system.EntityFramework.DAL.TestContext.MasterSchema;
using production_supply_system.EntityFramework.DAL.TestContext.PartscontrolSchema;
using production_supply_system.EntityFramework.DAL.TestContext.PlanningSchema;
using production_supply_system.EntityFramework.DAL.TestContext.UsersSchema;


namespace production_supply_system.EntityFramework.DAL.TestContext.InboundSchema;

[Table("tbd_Tracing", Schema = "Inbound")]
public partial class TbdTracing
{
    [Key]
    [Column("Tracing_Id")]
    public int TracingId { get; set; }

    [Column("Container_In_Lot_Id")]
    public int ContainerInLotId { get; set; }

    [Column("Carrier_Id")]
    public int? CarrierId { get; set; }

    [Column("Trace_Transport_Id")]
    public int? TraceTransportId { get; set; }

    [Column("Transportation_Type_Id")]
    public int? TransportationTypeId { get; set; }

    [Column("Trace_Location_Id")]
    public int TraceLocationId { get; set; }

    [Column("Trace_Transport_Document")]
    [StringLength(50)]
    public string? TraceTransportDocument { get; set; }

    [Column("Trace_ETA")]
    public DateOnly? TraceEta { get; set; }

    [Column("Trace_ATA")]
    public DateOnly? TraceAta { get; set; }

    [Column("Trace_ETD")]
    public DateOnly? TraceEtd { get; set; }

    [Column("Trace_ATD")]
    public DateOnly? TraceAtd { get; set; }

    [ForeignKey("CarrierId")]
    [InverseProperty("TbdTracings")]
    public virtual TbdCarrier? Carrier { get; set; }

    [ForeignKey("ContainerInLotId")]
    [InverseProperty("TbdTracings")]
    public virtual TbdContainersInLot ContainerInLot { get; set; } = null!;

    [ForeignKey("TraceLocationId")]
    [InverseProperty("TbdTracings")]
    public virtual TbdLocation TraceLocation { get; set; } = null!;

    [ForeignKey("TraceTransportId")]
    [InverseProperty("TbdTracings")]
    public virtual TbdTransport? TraceTransport { get; set; }

    [ForeignKey("TransportationTypeId")]
    [InverseProperty("TbdTracings")]
    public virtual TbdTypesOfTransport? TransportationType { get; set; }
}