// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using production_supply_system.EntityFramework.DAL.TestContext.CustomsSchema;
using production_supply_system.EntityFramework.DAL.TestContext.dboSchema;
using production_supply_system.EntityFramework.DAL.TestContext.DocmapperSchema;
using production_supply_system.EntityFramework.DAL.TestContext.InboundSchema;
using production_supply_system.EntityFramework.DAL.TestContext.MasterSchema;
using production_supply_system.EntityFramework.DAL.TestContext.PartscontrolSchema;
using production_supply_system.EntityFramework.DAL.TestContext.PlanningSchema;
using production_supply_system.EntityFramework.DAL.TestContext.UsersSchema;


namespace production_supply_system.EntityFramework.DAL.TestContext.InboundSchema;

[Table("tbd_Types_Of_Part", Schema = "Inbound")]
public partial class TbdTypesOfPart
{
    [Key]
    [Column("Part_Type_Id")]
    public int PartTypeId { get; set; }

    [Column("Part_Type")]
    [StringLength(10)]
    public string PartType { get; set; } = null!;

    [InverseProperty("PartType")]
    public virtual ICollection<TbdCustomsClearance> TbdCustomsClearances { get; set; } = new List<TbdCustomsClearance>();

    [InverseProperty("PartType")]
    public virtual ICollection<TbdCustomsPart> TbdCustomsParts { get; set; } = new List<TbdCustomsPart>();
}